export const variableDescriptions = {

  "birdAlligator_nogoN2_amplitude30": "N2 amplitude during No-Go trials (30 months)",
  "birdAlligator_nogoN2_amplitude36": "N2 amplitude during No-Go trials (36 months)",
  "birdAlligator_nogoN2_amplitude42": "N2 amplitude during No-Go trials (42 months)",
  "birdAlligator_nogoN2_amplitude54": "N2 amplitude during No-Go trials (54 months)",
  "birdAlligator_nogoN2_amplitudeMean": "Mean N2 amplitude during No-Go trials across timepoints",

  "birdAlligator_goN2_amplitude30": "N2 amplitude during Go trials (30 months)",
  "birdAlligator_goN2_amplitude36": "N2 amplitude during Go trials (36 months)",
  "birdAlligator_goN2_amplitude42": "N2 amplitude during Go trials (42 months)",
  "birdAlligator_goN2_amplitude54": "N2 amplitude during Go trials (54 months)",
  "birdAlligator_goN2_amplitudeMean": "Mean N2 amplitude during Go trials across timepoints",

  "birdAlligator_nogoN2_amplitudeCentered30": "Mean-centered N2 amplitude during No-Go trials (30 months)",
  "birdAlligator_nogoN2_amplitudeCentered36": "Mean-centered N2 amplitude during No-Go trials (36 months)",
  "birdAlligator_nogoN2_amplitudeCentered42": "Mean-centered N2 amplitude during No-Go trials (42 months)",
  "birdAlligator_nogoN2_amplitudeCentered54": "Mean-centered N2 amplitude during No-Go trials (54 months)",
  "birdAlligator_nogoN2_amplitudeCenteredMean": "Mean-centered N2 amplitude during No-Go trials (across timepoints)",

  "birdAlligator_goN2_amplitudeCentered30": "Mean-centered N2 amplitude during Go trials (30 months)",
  "birdAlligator_goN2_amplitudeCentered36": "Mean-centered N2 amplitude during Go trials (36 months)",
  "birdAlligator_goN2_amplitudeCentered42": "Mean-centered N2 amplitude during Go trials (42 months)",
  "birdAlligator_goN2_amplitudeCentered54": "Mean-centered N2 amplitude during Go trials (54 months)",
  "birdAlligator_goN2_amplitudeCenteredMean": "Mean-centered N2 amplitude during Go trials (across timepoints)",

  "birdAlligator_N2_amplitudeDifference30": "No-Go minus Go N2 amplitude (30 months)",
  "birdAlligator_N2_amplitudeDifference36": "No-Go minus Go N2 amplitude (36 months)",
  "birdAlligator_N2_amplitudeDifference42": "No-Go minus Go N2 amplitude (42 months)",
  "birdAlligator_N2_amplitudeDifference54": "No-Go minus Go N2 amplitude (54 months)",
  "birdAlligator_N2_amplitudeDifferenceMean": "No-Go minus Go N2 amplitude (across timepoints)",

  "birdAlligator_N2_amplitudeDifferenceCentered30": "Mean-centered N2 amplitude difference (30 months)",
  "birdAlligator_N2_amplitudeDifferenceCentered36": "Mean-centered N2 amplitude difference (36 months)",
  "birdAlligator_N2_amplitudeDifferenceCentered42": "Mean-centered N2 amplitude difference (42 months)",
  "birdAlligator_N2_amplitudeDifferenceCentered54": "Mean-centered N2 amplitude difference (54 months)",
  "birdAlligator_N2_amplitudeDifferenceCenteredMean": "Mean-centered N2 amplitude difference (across timepoints)",

  "birdAlligator_nogoN2_latency30": "Latency to N2 peak during No-Go trials (30 months)",
  "birdAlligator_nogoN2_latency36": "Latency to N2 peak during No-Go trials (36 months)",
  "birdAlligator_nogoN2_latency42": "Latency to N2 peak during No-Go trials (42 months)",
  "birdAlligator_nogoN2_latency54": "Latency to N2 peak during No-Go trials (54 months)",
  "birdAlligator_nogoN2_latencyMean": "Mean N2 latency during No-Go trials across timepoints",

  "birdAlligator_goN2_latency30": "Latency to N2 peak during Go trials (30 months)",
  "birdAlligator_goN2_latency36": "Latency to N2 peak during Go trials (36 months)",
  "birdAlligator_goN2_latency42": "Latency to N2 peak during Go trials (42 months)",
  "birdAlligator_goN2_latency54": "Latency to N2 peak during Go trials (54 months)",
  "birdAlligator_goN2_latencyMean": "Mean N2 latency during Go trials across timepoints",

  "birdAlligator_nogoN2_latencyCentered30": "Mean-centered N2 latency during No-Go trials (30 months)",
  "birdAlligator_nogoN2_latencyCentered36": "Mean-centered N2 latency during No-Go trials (36 months)",
  "birdAlligator_nogoN2_latencyCentered42": "Mean-centered N2 latency during No-Go trials (42 months)",
  "birdAlligator_nogoN2_latencyCentered54": "Mean-centered N2 latency during No-Go trials (54 months)",
  "birdAlligator_nogoN2_latencyCenteredMean": "Mean-centered N2 latency during No-Go trials (across timepoints)",

  "birdAlligator_goN2_latencyCentered30": "Mean-centered N2 latency during Go trials (30 months)",
  "birdAlligator_goN2_latencyCentered36": "Mean-centered N2 latency during Go trials (36 months)",
  "birdAlligator_goN2_latencyCentered42": "Mean-centered N2 latency during Go trials (42 months)",
  "birdAlligator_goN2_latencyCentered54": "Mean-centered N2 latency during Go trials (54 months)",
  "birdAlligator_goN2_latencyCenteredMean": "Mean-centered N2 latency during Go trials (across timepoints)",

  "birdAlligatorFrontalThetaTF30": "Frontal theta time-frequency activity (30 months)",
  "birdAlligatorFrontalThetaTF36": "Frontal theta time-frequency activity (36 months)",
  "birdAlligatorFrontalThetaTF42": "Frontal theta time-frequency activity (42 months)",
  "birdAlligatorFrontalThetaTF54": "Frontal theta time-frequency activity (54 months)",
  "birdAlligatorFrontalThetaTFMean": "Frontal theta time-frequency activity (across timepoints)",

  "birdAlligatorFrontalAlphaPower30": "Frontal alpha power (30 months)",
  "birdAlligatorFrontalAlphaPower36": "Frontal alpha power (36 months)",
  "birdAlligatorFrontalAlphaPower42": "Frontal alpha power (42 months)",
  "birdAlligatorFrontalAlphaPower54": "Frontal alpha power (54 months)",
  "birdAlligatorFrontalAlphaPowerMean": "Frontal alpha power (across timepoints)",

  "birdAlligatorFrontalAlphaPowerLog30": "Log-transformed frontal alpha power (30 months)",
  "birdAlligatorFrontalAlphaPowerLog36": "Log-transformed frontal alpha power (36 months)",
  "birdAlligatorFrontalAlphaPowerLog42": "Log-transformed frontal alpha power (42 months)",
  "birdAlligatorFrontalAlphaPowerLog54": "Log-transformed frontal alpha power (54 months)",
  "birdAlligatorFrontalAlphaPowerLogMean": "Log-transformed frontal alpha power (across timepoints)",

  "birdAlligatorPosteriorAlphaPowerLog30": "Log-transformed posterior alpha power (30 months)",
  "birdAlligatorPosteriorAlphaPowerLog36": "Log-transformed posterior alpha power (36 months)",
  "birdAlligatorPosteriorAlphaPowerLog42": "Log-transformed posterior alpha power (42 months)",
  "birdAlligatorPosteriorAlphaPowerLog54": "Log-transformed posterior alpha power (54 months)",
  "birdAlligatorPosteriorAlphaPowerLogMean": "Log-transformed posterior alpha power (across timepoints)",

  "birdAlligatorFrontalThetaPowerLog30": "Log-transformed frontal theta power (30 months)",
  "birdAlligatorFrontalThetaPowerLog36": "Log-transformed frontal theta power (36 months)",
  "birdAlligatorFrontalThetaPowerLog42": "Log-transformed frontal theta power (42 months)",
  "birdAlligatorFrontalThetaPowerLog54": "Log-transformed frontal theta power (54 months)",
  "birdAlligatorFrontalThetaPowerLogMean": "Log-transformed frontal theta power (across timepoints)",

  "birdAlligatorFrontalAsymmetry30": "Frontal EEG asymmetry (30 months)",
  "birdAlligatorFrontalAsymmetry36": "Frontal EEG asymmetry (36 months)",
  "birdAlligatorFrontalAsymmetry42": "Frontal EEG asymmetry (42 months)",
  "birdAlligatorFrontalAsymmetry54": "Frontal EEG asymmetry (54 months)",
  "birdAlligatorFrontalAsymmetryMean": "Frontal EEG asymmetry (across timepoints)",

  "eegBirdAlligatorMissing30": "Missing EEG data indicator (30 months)",
  "eegBirdAlligatorMissing36": "Missing EEG data indicator (36 months)",
  "eegBirdAlligatorMissing42": "Missing EEG data indicator (42 months)",
  "eegBirdAlligatorMissing54": "Missing EEG data indicator (54 months)",
  "eegBirdAlligatorMissingMean": "Missing EEG data indicator (across timepoints)",

  "eegBirdAlligatorBadChannels30": "Indicator of bad EEG channels (30 months)",
  "eegBirdAlligatorBadChannels36": "Indicator of bad EEG channels (36 months)",
  "eegBirdAlligatorBadChannels42": "Indicator of bad EEG channels (42 months)",
  "eegBirdAlligatorBadChannels54": "Indicator of bad EEG channels (54 months)",
  "eegBirdAlligatorBadChannelsMean": "Indicator of bad EEG channels (across timepoints)",

  "eegBirdAlligatorGoKeep30": "Number of Go trials retained (30 months)",
  "eegBirdAlligatorGoKeep36": "Number of Go trials retained (36 months)",
  "eegBirdAlligatorGoKeep42": "Number of Go trials retained (42 months)",
  "eegBirdAlligatorGoKeep54": "Number of Go trials retained (54 months)",
  "eegBirdAlligatorGoKeepMean": "Number of Go trials retained (across timepoints)",

  "eegBirdAlligatorNogoKeep30": "Number of No-Go trials retained (30 months)",
  "eegBirdAlligatorNogoKeep36": "Number of No-Go trials retained (36 months)",
  "eegBirdAlligatorNogoKeep42": "Number of No-Go trials retained (42 months)",
  "eegBirdAlligatorNogoKeep54": "Number of No-Go trials retained (54 months)",
  "eegBirdAlligatorNogoKeepMean": "Number of No-Go trials retained (across timepoints)",

  "eegBirdAlligatorGoPercentCorrect30": "Percent correct on Go trials (30 months)",
  "eegBirdAlligatorGoPercentCorrect36": "Percent correct on Go trials (36 months)",
  "eegBirdAlligatorGoPercentCorrect42": "Percent correct on Go trials (42 months)",
  "eegBirdAlligatorGoPercentCorrect54": "Percent correct on Go trials (54 months)",
  "eegBirdAlligatorGoPercentCorrectMean": "Percent correct on Go trials (across timepoints)",

  "eegBirdAlligatorNogoPercentCorrect30": "Percent correct on No-Go trials (30 months)",
  "eegBirdAlligatorNogoPercentCorrect36": "Percent correct on No-Go trials (36 months)",
  "eegBirdAlligatorNogoPercentCorrect42": "Percent correct on No-Go trials (42 months)",
  "eegBirdAlligatorNogoPercentCorrect54": "Percent correct on No-Go trials (54 months)",
  "eegBirdAlligatorNogoPercentCorrectMean": "Percent correct on No-Go trials (across timepoints)",

  "eegBirdAlligatorNumberBadChannels30": "Number of bad EEG channels (30 months)",
  "eegBirdAlligatorNumberBadChannels36": "Number of bad EEG channels (36 months)",
  "eegBirdAlligatorNumberBadChannels42": "Number of bad EEG channels (42 months)",
  "eegBirdAlligatorNumberBadChannels54": "Number of bad EEG channels (54 months)",
  "eegBirdAlligatorNumberBadChannelsMean": "Number of bad EEG channels (across timepoints)",

  "birdAlligatorChildPres30": "Other child present during task (30 months)",
  "birdAlligatorChildPres36": "Other child present during task (36 months)",
  "birdAlligatorChildPres42": "Other child present during task (42 months)",
  "birdAlligatorChildPres54": "Other child present during task (54 months)",

  "birdAlligatorParentPres30": "Parent present during task (30 months)",
  "birdAlligatorParentPres36": "Parent present during task (36 months)",
  "birdAlligatorParentPres42": "Parent present during task (42 months)",
  "birdAlligatorParentPres54": "Parent present during task (54 months)",

  "birdAlligatorPassedGoPracticeTrials30": "Passed Go practice trials (30 months)",
  "birdAlligatorPassedGoPracticeTrials36": "Passed Go practice trials (36 months)",
  "birdAlligatorPassedGoPracticeTrials42": "Passed Go practice trials (42 months)",
  "birdAlligatorPassedGoPracticeTrials54": "Passed Go practice trials (54 months)",

  "birdAlligatorPassedNogoPracticeTrials30": "Passed No-Go practice trials (30 months)",
  "birdAlligatorPassedNogoPracticeTrials36": "Passed No-Go practice trials (36 months)",
  "birdAlligatorPassedNogoPracticeTrials42": "Passed No-Go practice trials (42 months)",
  "birdAlligatorPassedNogoPracticeTrials54": "Passed No-Go practice trials (54 months)",

  "birdAlligatorGo30": "Mean accuracy on Go trials (30 months)",
  "birdAlligatorGo36": "Mean accuracy on Go trials (36 months)",
  "birdAlligatorGo42": "Mean accuracy on Go trials (42 months)",
  "birdAlligatorGo54": "Mean accuracy on Go trials (54 months)",
  "birdAlligatorGoMean": "Mean accuracy on Go trials (across timepoints)",

  "birdAlligatorGoRuleSwitch30": "Go performance during rule-switch block (30 months)",
  "birdAlligatorGoRuleSwitch36": "Go performance during rule-switch block (36 months)",
  "birdAlligatorGoRuleSwitch42": "Go performance during rule-switch block (42 months)",
  "birdAlligatorGoRuleSwitch54": "Go performance during rule-switch block (54 months)",
  "birdAlligatorGoRuleSwitchMean": "Go performance during rule-switch block (across timepoints)",

  "birdAlligatorGoTotal30": "Go performance across all trials (30 months)",
  "birdAlligatorGoTotal36": "Go performance across all trials (36 months)",
  "birdAlligatorGoTotal42": "Go performance across all trials (42 months)",
  "birdAlligatorGoTotal54": "Go performance across all trials (54 months)",
  "birdAlligatorGoTotalMean": "Go performance across all trials (across timepoints)",

  "birdAlligatorNogo30": "Mean accuracy on No-Go trials (30 months)",
  "birdAlligatorNogo36": "Mean accuracy on No-Go trials (36 months)",
  "birdAlligatorNogo42": "Mean accuracy on No-Go trials (42 months)",
  "birdAlligatorNogo54": "Mean accuracy on No-Go trials (54 months)",
  "birdAlligatorNogoMean": "Mean accuracy on No-Go trials (across timepoints)",

  "birdAlligatorNogoRuleSwitch30": "No-Go performance during rule-switch block (30 months)",
  "birdAlligatorNogoRuleSwitch36": "No-Go performance during rule-switch block (36 months)",
  "birdAlligatorNogoRuleSwitch42": "No-Go performance during rule-switch block (42 months)",
  "birdAlligatorNogoRuleSwitch54": "No-Go performance during rule-switch block (54 months)",
  "birdAlligatorNogoRuleSwitchMean": "No-Go performance during rule-switch block (across timepoints)",

  "birdAlligatorNogoTotal30": "No-Go performance across all trials (30 months)",
  "birdAlligatorNogoTotal36": "No-Go performance across all trials (36 months)",
  "birdAlligatorNogoTotal42": "No-Go performance across all trials (42 months)",
  "birdAlligatorNogoTotal54": "No-Go performance across all trials (54 months)",
  "birdAlligatorNogoTotalMean": "No-Go performance across all trials (across timepoints)",

  "birdAlligatorGoXNogo30": "Go × No-Go combined performance (30 months)",
  "birdAlligatorGoXNogo36": "Go × No-Go combined performance (36 months)",
  "birdAlligatorGoXNogo42": "Go × No-Go combined performance (42 months)",
  "birdAlligatorGoXNogo54": "Go × No-Go combined performance (54 months)",
  "birdAlligatorGoXNogoMean": "Go × No-Go combined performance (across timepoints)",

  "birdAlligatorGoXNogoRuleSwitch30": "Combined performance during rule-switch block (30 months)",
  "birdAlligatorGoXNogoRuleSwitch36": "Combined performance during rule-switch block (36 months)",
  "birdAlligatorGoXNogoRuleSwitch42": "Combined performance during rule-switch block (42 months)",
  "birdAlligatorGoXNogoRuleSwitch54": "Combined performance during rule-switch block (54 months)",
  "birdAlligatorGoXNogoRuleSwitchMean": "Combined performance during rule-switch block (across timepoints)",

  "birdAlligatorGoXNogoTotal30": "Combined performance across all trials (30 months)",
  "birdAlligatorGoXNogoTotal36": "Combined performance across all trials (36 months)",
  "birdAlligatorGoXNogoTotal42": "Combined performance across all trials (42 months)",
  "birdAlligatorGoXNogoTotal54": "Combined performance across all trials (54 months)",
  "birdAlligatorGoXNogoTotalMean": "Combined performance across all trials (across timepoints)",

  "birdAlligatorInhibition30": "Inhibitory control composite (30 months)",
  "birdAlligatorInhibition36": "Inhibitory control composite (36 months)",
  "birdAlligatorInhibition42": "Inhibitory control composite (42 months)",
  "birdAlligatorInhibition54": "Inhibitory control composite (54 months)",
  "birdAlligatorInhibitionMean": "Inhibitory control composite (across timepoints)",

  "birdAlligatorGoImputed30": "Go performance with imputed missing values (30 months)",
  "birdAlligatorGoImputed36": "Go performance with imputed missing values (36 months)",
  "birdAlligatorGoImputed42": "Go performance with imputed missing values (42 months)",
  "birdAlligatorGoImputed54": "Go performance with imputed missing values (54 months)",
  "birdAlligatorGoImputedMean": "Go performance with imputed missing values (across timepoints)",

  "birdAlligatorNogoImputed30": "No-Go performance with imputed missing values (30 months)",
  "birdAlligatorNogoImputed36": "No-Go performance with imputed missing values (36 months)",
  "birdAlligatorNogoImputed42": "No-Go performance with imputed missing values (42 months)",
  "birdAlligatorNogoImputed54": "No-Go performance with imputed missing values (54 months)",
  "birdAlligatorNogoImputedMean": "No-Go performance with imputed missing values (across timepoints)",

  "birdAlligatorGoXNogoImputed30": "Combined Go × No-Go score using imputed values (30 months)",
  "birdAlligatorGoXNogoImputed36": "Combined Go × No-Go score using imputed values (36 months)",
  "birdAlligatorGoXNogoImputed42": "Combined Go × No-Go score using imputed values (42 months)",
  "birdAlligatorGoXNogoImputed54": "Combined Go × No-Go score using imputed values (54 months)",
  "birdAlligatorGoXNogoImputedMean": "Combined Go × No-Go score using imputed values (across timepoints)",

  "birdAlligatorInhibitionImputed30": "Inhibition composite using imputed values (30 months)",
  "birdAlligatorInhibitionImputed36": "Inhibition composite using imputed values (36 months)",
  "birdAlligatorInhibitionImputed42": "Inhibition composite using imputed values (42 months)",
  "birdAlligatorInhibitionImputed54": "Inhibition composite using imputed values (54 months)",
  "birdAlligatorInhibitionImputedMean": "Inhibition composite using imputed values (across timepoints)",

  "blhcOutdoorSum30": "Outdoor behavior composite score (BLHC measure) (30 months)",
  "blhcOutdoorSum36": "Outdoor behavior composite score (BLHC measure) (36 months)",
  "blhcOutdoorSum42": "Outdoor behavior composite score (BLHC measure) (42 months)",
  "blhcOutdoorSum54": "Outdoor behavior composite score (BLHC measure) (54 months)",

  "doorOpeningChildPres30": "Door Opening - Other Child Present? (30 months)",
  "doorOpeningChildPres36": "Door Opening - Other Child Present? (36 months)",
  "doorOpeningChildPres42": "Door Opening - Other Child Present? (42 months)",
  "doorOpeningChildPres54": "Door Opening - Other Child Present? (54 months)",

  "doorOpeningParentPres30": "Door Opening - Parent Present? (30 months)",
  "doorOpeningParentPres36": "Door Opening - Parent Present? (36 months)",
  "doorOpeningParentPres42": "Door Opening - Parent Present? (42 months)",
  "doorOpeningParentPres54": "Door Opening - Parent Present? (54 months)",

  "doorOpeningDoorsOpened30": "Door Opening - Number of doors opened (not forced trials) (30 months)",
  "doorOpeningDoorsOpened36": "Door Opening - Number of doors opened (not forced trials) (36 months)",
  "doorOpeningDoorsOpened42": "Door Opening - Number of doors opened (not forced trials) (42 months)",
  "doorOpeningDoorsOpened54": "Door Opening - Number of doors opened (not forced trials) (54 months)",

  "doorOpeningForcedTrials30": "Door Opening - Number of forced trials (30 months)",
  "doorOpeningForcedTrials36": "Door Opening - Number of forced trials (36 months)",
  "doorOpeningForcedTrials42": "Door Opening - Number of forced trials (42 months)",
  "doorOpeningForcedTrials54": "Door Opening - Number of forced trials (54 months)",

  "doorOpeningDelaysAfterPunishment30": "Door Opening - Number of delays after a punishment (30 months)",
  "doorOpeningDelaysAfterPunishment36": "Door Opening - Number of delays after a punishment (36 months)",
  "doorOpeningDelaysAfterPunishment42": "Door Opening - Number of delays after a punishment (42 months)",
  "doorOpeningDelaysAfterPunishment54": "Door Opening - Number of delays after a punishment (54 months)",

  "doorOpeningDelaysAfterReward30": "Door Opening - Number of delays after a reward (30 months)",
  "doorOpeningDelaysAfterReward36": "Door Opening - Number of delays after a reward (36 months)",
  "doorOpeningDelaysAfterReward42": "Door Opening - Number of delays after a reward (42 months)",
  "doorOpeningDelaysAfterReward54": "Door Opening - Number of delays after a reward (54 months)",

  "doorOpeningDelayOfFirstTrial30": "Door Opening - Was there a delay on the first trial? (30 months)",
  "doorOpeningDelayOfFirstTrial36": "Door Opening - Was there a delay on the first trial? (36 months)",
  "doorOpeningDelayOfFirstTrial42": "Door Opening - Was there a delay on the first trial? (42 months)",
  "doorOpeningDelayOfFirstTrial54": "Door Opening - Was there a delay on the first trial? (54 months)",

  "doorOpeningComposite30": "Mean of doorsOpenedZ and forcedTrialsRZ (30 months)",
  "doorOpeningComposite36": "Mean of doorsOpenedZ and forcedTrialsRZ (36 months)",
  "doorOpeningComposite42": "Mean of doorsOpenedZ and forcedTrialsRZ (42 months)",
  "doorOpeningComposite54": "Mean of doorsOpenedZ and forcedTrialsRZ (54 months)",

  "doorOpeningRewardSensitivity30": "Doors opened minus 12; if <12 then 0 (reward sensitivity) (30 months)",
  "doorOpeningRewardSensitivity36": "Doors opened minus 12; if <12 then 0 (reward sensitivity) (36 months)",
  "doorOpeningRewardSensitivity42": "Doors opened minus 12; if <12 then 0 (reward sensitivity) (42 months)",
  "doorOpeningRewardSensitivity54": "Doors opened minus 12; if <12 then 0 (reward sensitivity) (54 months)",

  "doorOpeningPunishmentSensitivity30": "8 minus doors opened; if >8 then 0; <5 = NA (punishment sensitivity) (30 months)",
  "doorOpeningPunishmentSensitivity36": "8 minus doors opened; if >8 then 0; <5 = NA (punishment sensitivity) (36 months)",
  "doorOpeningPunishmentSensitivity42": "8 minus doors opened; if >8 then 0; <5 = NA (punishment sensitivity) (42 months)",
  "doorOpeningPunishmentSensitivity54": "8 minus doors opened; if >8 then 0; <5 = NA (punishment sensitivity) (54 months)",

  "fruitStroopChildPres30": "Fruit Stroop - Other child present? (30 months)",
  "fruitStroopChildPres36": "Fruit Stroop - Other child present? (36 months)",
  "fruitStroopChildPres42": "Fruit Stroop - Other child present? (42 months)",
  "fruitStroopChildPres54": "Fruit Stroop - Other child present? (54 months)",

  "fruitStroopParentPres30": "Fruit Stroop - Parent Present? (30 months)",
  "fruitStroopParentPres36": "Fruit Stroop - Parent Present? (36 months)",
  "fruitStroopParentPres42": "Fruit Stroop - Parent Present? (42 months)",
  "fruitStroopParentPres54": "Fruit Stroop - Parent Present? (54 months)",

  "fruitStroopSmall30": "Small fruit score; mean of fruitStroopSmall_T1, T2, & T3 (30 months)",
  "fruitStroopSmall36": "Small fruit score; mean of fruitStroopSmall_T1, T2, & T3 (36 months)",
  "fruitStroopSmall42": "Small fruit score; mean of fruitStroopSmall_T1, T2, & T3 (42 months)",
  "fruitStroopSmall54": "Small fruit score; mean of fruitStroopSmall_T1, T2, & T3 (54 months)",

  "fruitStroopLarge30": "Large fruit score; mean of fruitStroopLarge_T1, T2, & T3 (30 months)",
  "fruitStroopLarge36": "Large fruit score; mean of fruitStroopLarge_T1, T2, & T3 (36 months)",
  "fruitStroopLarge42": "Large fruit score; mean of fruitStroopLarge_T1, T2, & T3 (42 months)",
  "fruitStroopLarge54": "Large fruit score; mean of fruitStroopLarge_T1, T2, & T3 (54 months)",

  "fruitStroopAvg30": "Average of small & large fruit trials; mean of fruitStroopSmall & fruitStroopLarge (30 months)",
  "fruitStroopAvg36": "Average of small & large fruit trials; mean of fruitStroopSmall & fruitStroopLarge (36 months)",
  "fruitStroopAvg42": "Average of small & large fruit trials; mean of fruitStroopSmall & fruitStroopLarge (42 months)",
  "fruitStroopAvg54": "Average of small & large fruit trials; mean of fruitStroopSmall & fruitStroopLarge (54 months)",

};
