export const variableDescriptions = {

  "birdAlligator_nogoN2_amplitude30": "N2 amplitude during No-Go trials (30 months)",
  "birdAlligator_nogoN2_amplitude36": "N2 amplitude during No-Go trials (36 months)",
  "birdAlligator_nogoN2_amplitude42": "N2 amplitude during No-Go trials (42 months)",
  "birdAlligator_nogoN2_amplitude54": "N2 amplitude during No-Go trials (54 months)",
  "birdAlligator_nogoN2_amplitudeMean": "Mean N2 amplitude during No-Go trials across timepoints",

  "birdAlligator_goN2_amplitude30": "N2 amplitude during Go trials (30 months)",
  "birdAlligator_goN2_amplitude36": "N2 amplitude during Go trials (36 months)",
  "birdAlligator_goN2_amplitude42": "N2 amplitude during Go trials (42 months)",
  "birdAlligator_goN2_amplitude54": "N2 amplitude during Go trials (54 months)",
  "birdAlligator_goN2_amplitudeMean": "Mean N2 amplitude during Go trials across timepoints",

  "birdAlligator_nogoN2_amplitudeCentered30": "Mean-centered N2 amplitude during No-Go trials (30 months)",
  "birdAlligator_nogoN2_amplitudeCentered36": "Mean-centered N2 amplitude during No-Go trials (36 months)",
  "birdAlligator_nogoN2_amplitudeCentered42": "Mean-centered N2 amplitude during No-Go trials (42 months)",
  "birdAlligator_nogoN2_amplitudeCentered54": "Mean-centered N2 amplitude during No-Go trials (54 months)",
  "birdAlligator_nogoN2_amplitudeCenteredMean": "Mean-centered N2 amplitude during No-Go trials (across timepoints)",

  "birdAlligator_goN2_amplitudeCentered30": "Mean-centered N2 amplitude during Go trials (30 months)",
  "birdAlligator_goN2_amplitudeCentered36": "Mean-centered N2 amplitude during Go trials (36 months)",
  "birdAlligator_goN2_amplitudeCentered42": "Mean-centered N2 amplitude during Go trials (42 months)",
  "birdAlligator_goN2_amplitudeCentered54": "Mean-centered N2 amplitude during Go trials (54 months)",
  "birdAlligator_goN2_amplitudeCenteredMean": "Mean-centered N2 amplitude during Go trials (across timepoints)",

  "birdAlligator_N2_amplitudeDifference30": "No-Go minus Go N2 amplitude (30 months)",
  "birdAlligator_N2_amplitudeDifference36": "No-Go minus Go N2 amplitude (36 months)",
  "birdAlligator_N2_amplitudeDifference42": "No-Go minus Go N2 amplitude (42 months)",
  "birdAlligator_N2_amplitudeDifference54": "No-Go minus Go N2 amplitude (54 months)",
  "birdAlligator_N2_amplitudeDifferenceMean": "No-Go minus Go N2 amplitude (across timepoints)",

  "birdAlligator_N2_amplitudeDifferenceCentered30": "Mean-centered N2 amplitude difference (30 months)",
  "birdAlligator_N2_amplitudeDifferenceCentered36": "Mean-centered N2 amplitude difference (36 months)",
  "birdAlligator_N2_amplitudeDifferenceCentered42": "Mean-centered N2 amplitude difference (42 months)",
  "birdAlligator_N2_amplitudeDifferenceCentered54": "Mean-centered N2 amplitude difference (54 months)",
  "birdAlligator_N2_amplitudeDifferenceCenteredMean": "Mean-centered N2 amplitude difference (across timepoints)",

  "birdAlligator_nogoN2_latency30": "Latency to N2 peak during No-Go trials (30 months)",
  "birdAlligator_nogoN2_latency36": "Latency to N2 peak during No-Go trials (36 months)",
  "birdAlligator_nogoN2_latency42": "Latency to N2 peak during No-Go trials (42 months)",
  "birdAlligator_nogoN2_latency54": "Latency to N2 peak during No-Go trials (54 months)",
  "birdAlligator_nogoN2_latencyMean": "Mean N2 latency during No-Go trials across timepoints",

  "birdAlligator_goN2_latency30": "Latency to N2 peak during Go trials (30 months)",
  "birdAlligator_goN2_latency36": "Latency to N2 peak during Go trials (36 months)",
  "birdAlligator_goN2_latency42": "Latency to N2 peak during Go trials (42 months)",
  "birdAlligator_goN2_latency54": "Latency to N2 peak during Go trials (54 months)",
  "birdAlligator_goN2_latencyMean": "Mean N2 latency during Go trials across timepoints",

  "birdAlligator_nogoN2_latencyCentered30": "Mean-centered N2 latency during No-Go trials (30 months)",
  "birdAlligator_nogoN2_latencyCentered36": "Mean-centered N2 latency during No-Go trials (36 months)",
  "birdAlligator_nogoN2_latencyCentered42": "Mean-centered N2 latency during No-Go trials (42 months)",
  "birdAlligator_nogoN2_latencyCentered54": "Mean-centered N2 latency during No-Go trials (54 months)",
  "birdAlligator_nogoN2_latencyCenteredMean": "Mean-centered N2 latency during No-Go trials (across timepoints)",

  "birdAlligator_goN2_latencyCentered30": "Mean-centered N2 latency during Go trials (30 months)",
  "birdAlligator_goN2_latencyCentered36": "Mean-centered N2 latency during Go trials (36 months)",
  "birdAlligator_goN2_latencyCentered42": "Mean-centered N2 latency during Go trials (42 months)",
  "birdAlligator_goN2_latencyCentered54": "Mean-centered N2 latency during Go trials (54 months)",
  "birdAlligator_goN2_latencyCenteredMean": "Mean-centered N2 latency during Go trials (across timepoints)",

  "birdAlligatorFrontalThetaTF30": "Frontal theta time-frequency activity (30 months)",
  "birdAlligatorFrontalThetaTF36": "Frontal theta time-frequency activity (36 months)",
  "birdAlligatorFrontalThetaTF42": "Frontal theta time-frequency activity (42 months)",
  "birdAlligatorFrontalThetaTF54": "Frontal theta time-frequency activity (54 months)",
  "birdAlligatorFrontalThetaTFMean": "Frontal theta time-frequency activity (across timepoints)",

  "birdAlligatorFrontalAlphaPower30": "Frontal alpha power (30 months)",
  "birdAlligatorFrontalAlphaPower36": "Frontal alpha power (36 months)",
  "birdAlligatorFrontalAlphaPower42": "Frontal alpha power (42 months)",
  "birdAlligatorFrontalAlphaPower54": "Frontal alpha power (54 months)",
  "birdAlligatorFrontalAlphaPowerMean": "Frontal alpha power (across timepoints)",

  "birdAlligatorFrontalAlphaPowerLog30": "Log-transformed frontal alpha power (30 months)",
  "birdAlligatorFrontalAlphaPowerLog36": "Log-transformed frontal alpha power (36 months)",
  "birdAlligatorFrontalAlphaPowerLog42": "Log-transformed frontal alpha power (42 months)",
  "birdAlligatorFrontalAlphaPowerLog54": "Log-transformed frontal alpha power (54 months)",
  "birdAlligatorFrontalAlphaPowerLogMean": "Log-transformed frontal alpha power (across timepoints)",

  "birdAlligatorPosteriorAlphaPowerLog30": "Log-transformed posterior alpha power (30 months)",
  "birdAlligatorPosteriorAlphaPowerLog36": "Log-transformed posterior alpha power (36 months)",
  "birdAlligatorPosteriorAlphaPowerLog42": "Log-transformed posterior alpha power (42 months)",
  "birdAlligatorPosteriorAlphaPowerLog54": "Log-transformed posterior alpha power (54 months)",
  "birdAlligatorPosteriorAlphaPowerLogMean": "Log-transformed posterior alpha power (across timepoints)",

  "birdAlligatorFrontalThetaPowerLog30": "Log-transformed frontal theta power (30 months)",
  "birdAlligatorFrontalThetaPowerLog36": "Log-transformed frontal theta power (36 months)",
  "birdAlligatorFrontalThetaPowerLog42": "Log-transformed frontal theta power (42 months)",
  "birdAlligatorFrontalThetaPowerLog54": "Log-transformed frontal theta power (54 months)",
  "birdAlligatorFrontalThetaPowerLogMean": "Log-transformed frontal theta power (across timepoints)",

  "birdAlligatorFrontalAsymmetry30": "Frontal EEG asymmetry (30 months)",
  "birdAlligatorFrontalAsymmetry36": "Frontal EEG asymmetry (36 months)",
  "birdAlligatorFrontalAsymmetry42": "Frontal EEG asymmetry (42 months)",
  "birdAlligatorFrontalAsymmetry54": "Frontal EEG asymmetry (54 months)",
  "birdAlligatorFrontalAsymmetryMean": "Frontal EEG asymmetry (across timepoints)",

  "eegBirdAlligatorMissing30": "Missing EEG data indicator (30 months)",
  "eegBirdAlligatorMissing36": "Missing EEG data indicator (36 months)",
  "eegBirdAlligatorMissing42": "Missing EEG data indicator (42 months)",
  "eegBirdAlligatorMissing54": "Missing EEG data indicator (54 months)",
  "eegBirdAlligatorMissingMean": "Missing EEG data indicator (across timepoints)",

  "eegBirdAlligatorBadChannels30": "Indicator of bad EEG channels (30 months)",
  "eegBirdAlligatorBadChannels36": "Indicator of bad EEG channels (36 months)",
  "eegBirdAlligatorBadChannels42": "Indicator of bad EEG channels (42 months)",
  "eegBirdAlligatorBadChannels54": "Indicator of bad EEG channels (54 months)",
  "eegBirdAlligatorBadChannelsMean": "Indicator of bad EEG channels (across timepoints)",

  "eegBirdAlligatorGoKeep30": "Number of Go trials retained (30 months)",
  "eegBirdAlligatorGoKeep36": "Number of Go trials retained (36 months)",
  "eegBirdAlligatorGoKeep42": "Number of Go trials retained (42 months)",
  "eegBirdAlligatorGoKeep54": "Number of Go trials retained (54 months)",
  "eegBirdAlligatorGoKeepMean": "Number of Go trials retained (across timepoints)",

  "eegBirdAlligatorNogoKeep30": "Number of No-Go trials retained (30 months)",
  "eegBirdAlligatorNogoKeep36": "Number of No-Go trials retained (36 months)",
  "eegBirdAlligatorNogoKeep42": "Number of No-Go trials retained (42 months)",
  "eegBirdAlligatorNogoKeep54": "Number of No-Go trials retained (54 months)",
  "eegBirdAlligatorNogoKeepMean": "Number of No-Go trials retained (across timepoints)",

  "eegBirdAlligatorGoPercentCorrect30": "Percent correct on Go trials (30 months)",
  "eegBirdAlligatorGoPercentCorrect36": "Percent correct on Go trials (36 months)",
  "eegBirdAlligatorGoPercentCorrect42": "Percent correct on Go trials (42 months)",
  "eegBirdAlligatorGoPercentCorrect54": "Percent correct on Go trials (54 months)",
  "eegBirdAlligatorGoPercentCorrectMean": "Percent correct on Go trials (across timepoints)",

  "eegBirdAlligatorNogoPercentCorrect30": "Percent correct on No-Go trials (30 months)",
  "eegBirdAlligatorNogoPercentCorrect36": "Percent correct on No-Go trials (36 months)",
  "eegBirdAlligatorNogoPercentCorrect42": "Percent correct on No-Go trials (42 months)",
  "eegBirdAlligatorNogoPercentCorrect54": "Percent correct on No-Go trials (54 months)",
  "eegBirdAlligatorNogoPercentCorrectMean": "Percent correct on No-Go trials (across timepoints)",

  "eegBirdAlligatorNumberBadChannels30": "Number of bad EEG channels (30 months)",
  "eegBirdAlligatorNumberBadChannels36": "Number of bad EEG channels (36 months)",
  "eegBirdAlligatorNumberBadChannels42": "Number of bad EEG channels (42 months)",
  "eegBirdAlligatorNumberBadChannels54": "Number of bad EEG channels (54 months)",
  "eegBirdAlligatorNumberBadChannelsMean": "Number of bad EEG channels (across timepoints)",

  "birdAlligatorChildPres30": "Other child present during task",
  "birdAlligatorChildPres36": "Other child present during task",
  "birdAlligatorChildPres42": "Other child present during task",
  "birdAlligatorChildPres54": "Other child present during task",

  "birdAlligatorParentPres30": "Parent present during task",
  "birdAlligatorParentPres36": "Parent present during task",
  "birdAlligatorParentPres42": "Parent present during task",
  "birdAlligatorParentPres54": "Parent present during task",

  "birdAlligatorPassedGoPracticeTrials30": "Child passed Go practice trials",
  "birdAlligatorPassedGoPracticeTrials36": "Child passed Go practice trials",
  "birdAlligatorPassedGoPracticeTrials42": "Child passed Go practice trials",
  "birdAlligatorPassedGoPracticeTrials54": "Child passed Go practice trials",

  "birdAlligatorPassedNogoPracticeTrials30": "Child passed No-Go practice trials",
  "birdAlligatorPassedNogoPracticeTrials36": "Child passed No-Go practice trials",
  "birdAlligatorPassedNogoPracticeTrials42": "Child passed No-Go practice trials",
  "birdAlligatorPassedNogoPracticeTrials54": "Child passed No-Go practice trials",

  "birdAlligatorGo30": "Mean score on Go trials",
  "birdAlligatorGo36": "Mean score on Go trials",
  "birdAlligatorGo42": "Mean score on Go trials",
  "birdAlligatorGo54": "Mean score on Go trials",
  "birdAlligatorGoMean": "Mean accuracy on Go trials (across timepoints)",

  "birdAlligatorGoRuleSwitch30": "Go performance during rule-switch block",
  "birdAlligatorGoRuleSwitch36": "Go performance during rule-switch block",
  "birdAlligatorGoRuleSwitch42": "Go performance during rule-switch block",
  "birdAlligatorGoRuleSwitch54": "Go performance during rule-switch block",
  "birdAlligatorGoRuleSwitchMean": "Go performance during rule-switch block (across timepoints)",

  "birdAlligatorGoTotal30": "Go performance across all task blocks",
  "birdAlligatorGoTotal36": "Go performance across all task blocks",
  "birdAlligatorGoTotal42": "Go performance across all task blocks",
  "birdAlligatorGoTotal54": "Go performance across all task blocks",
  "birdAlligatorGoTotalMean": "Go performance across all trials (across timepoints)",

  "birdAlligatorNogo30": "Mean score on No-Go trials",
  "birdAlligatorNogo36": "Mean score on No-Go trials",
  "birdAlligatorNogo42": "Mean score on No-Go trials",
  "birdAlligatorNogo54": "Mean score on No-Go trials",
  "birdAlligatorNogoMean": "Mean accuracy on No-Go trials (across timepoints)",

  "birdAlligatorNogoRuleSwitch30": "No-Go performance during rule-switch block",
  "birdAlligatorNogoRuleSwitch36": "No-Go performance during rule-switch block",
  "birdAlligatorNogoRuleSwitch42": "No-Go performance during rule-switch block",
  "birdAlligatorNogoRuleSwitch54": "No-Go performance during rule-switch block",
  "birdAlligatorNogoRuleSwitchMean": "No-Go performance during rule-switch block (across timepoints)",

  "birdAlligatorNogoTotal30": "No-Go performance across all task blocks",
  "birdAlligatorNogoTotal36": "No-Go performance across all task blocks",
  "birdAlligatorNogoTotal42": "No-Go performance across all task blocks",
  "birdAlligatorNogoTotal54": "No-Go performance across all task blocks",
  "birdAlligatorNogoTotalMean": "No-Go performance across all trials (across timepoints)",

  "birdAlligatorGoXNogo30": "Mean Go score × Mean No-Go score",
  "birdAlligatorGoXNogo36": "Mean Go score × Mean No-Go score",
  "birdAlligatorGoXNogo42": "Mean Go score × Mean No-Go score",
  "birdAlligatorGoXNogo54": "Mean Go score × Mean No-Go score",
  "birdAlligatorGoXNogoMean": "Go × No-Go combined performance (across timepoints)",

  "birdAlligatorGoXNogoRuleSwitch30": "Go Rule Switch × No-Go Rule Switch performance",
  "birdAlligatorGoXNogoRuleSwitch36": "Go Rule Switch × No-Go Rule Switch performance",
  "birdAlligatorGoXNogoRuleSwitch42": "Go Rule Switch × No-Go Rule Switch performance",
  "birdAlligatorGoXNogoRuleSwitch54": "Go Rule Switch × No-Go Rule Switch performance",
  "birdAlligatorGoXNogoRuleSwitchMean": "Combined performance during rule-switch block (across timepoints)",

  "birdAlligatorGoXNogoTotal30": "Go Total × No-Go Total performance",
  "birdAlligatorGoXNogoTotal36": "Go Total × No-Go Total performance",
  "birdAlligatorGoXNogoTotal42": "Go Total × No-Go Total performance",
  "birdAlligatorGoXNogoTotal54": "Go Total × No-Go Total performance",
  "birdAlligatorGoXNogoTotalMean": "Combined performance across all trials (across timepoints)",

  "birdAlligatorInhibition30": "Mean of standardized No-Go and Go×No-Go scores (inhibitory control composite)",
  "birdAlligatorInhibition36": "Mean of standardized No-Go and Go×No-Go scores (inhibitory control composite)",
  "birdAlligatorInhibition42": "Mean of standardized No-Go and Go×No-Go scores (inhibitory control composite)",
  "birdAlligatorInhibition54": "Mean of standardized No-Go and Go×No-Go scores (inhibitory control composite)",
  "birdAlligatorInhibitionMean": "Inhibitory control composite (across timepoints)",

  "birdAlligatorGoImputed30": "Go score with missing values imputed as zero for children who passed practice",
  "birdAlligatorGoImputed36": "Go score with missing values imputed as zero for children who passed practice",
  "birdAlligatorGoImputed42": "Go score with missing values imputed as zero for children who passed practice",
  "birdAlligatorGoImputed54": "Go score with missing values imputed as zero for children who passed practice",
  "birdAlligatorGoImputedMean": "Go performance with imputed missing values (across timepoints)",

  "birdAlligatorNogoImputed30": "No-Go score with missing values imputed as zero for children who passed practice",
  "birdAlligatorNogoImputed36": "No-Go score with missing values imputed as zero for children who passed practice",
  "birdAlligatorNogoImputed42": "No-Go score with missing values imputed as zero for children who passed practice",
  "birdAlligatorNogoImputed54": "No-Go score with missing values imputed as zero for children who passed practice",
  "birdAlligatorNogoImputedMean": "No-Go performance with imputed missing values (across timepoints)",

  "birdAlligatorGoXNogoImputed30": "Imputed Go × No-Go composite",
  "birdAlligatorGoXNogoImputed36": "Imputed Go × No-Go composite",
  "birdAlligatorGoXNogoImputed42": "Imputed Go × No-Go composite",
  "birdAlligatorGoXNogoImputed54": "Imputed Go × No-Go composite",
  "birdAlligatorGoXNogoImputedMean": "Combined Go × No-Go score using imputed values (across timepoints)",

  "birdAlligatorInhibitionImputed30": "Inhibitory control composite based on imputed scores",
  "birdAlligatorInhibitionImputed36": "Inhibitory control composite based on imputed scores",
  "birdAlligatorInhibitionImputed42": "Inhibitory control composite based on imputed scores",
  "birdAlligatorInhibitionImputed54": "Inhibitory control composite based on imputed scores",
  "birdAlligatorInhibitionImputedMean": "Inhibition composite using imputed values (across timepoints)",

  "blhcOutdoorSum30": "Outdoor behavior composite score (BLHC measure) (30 months)",
  "blhcOutdoorSum36": "Outdoor behavior composite score (BLHC measure) (36 months)",
  "blhcOutdoorSum42": "Outdoor behavior composite score (BLHC measure) (42 months)",
  "blhcOutdoorSum54": "Outdoor behavior composite score (BLHC measure) (54 months)",

  "doorOpeningChildPres30": "Door Opening - Other Child Present? (30 months)",
  "doorOpeningChildPres36": "Door Opening - Other Child Present? (36 months)",
  "doorOpeningChildPres42": "Door Opening - Other Child Present? (42 months)",
  "doorOpeningChildPres54": "Door Opening - Other Child Present? (54 months)",

  "doorOpeningParentPres30": "Door Opening - Parent Present? (30 months)",
  "doorOpeningParentPres36": "Door Opening - Parent Present? (36 months)",
  "doorOpeningParentPres42": "Door Opening - Parent Present? (42 months)",
  "doorOpeningParentPres54": "Door Opening - Parent Present? (54 months)",

  "doorOpeningDoorsOpened30": "Door Opening - Number of doors opened (not forced trials) (30 months)",
  "doorOpeningDoorsOpened36": "Door Opening - Number of doors opened (not forced trials) (36 months)",
  "doorOpeningDoorsOpened42": "Door Opening - Number of doors opened (not forced trials) (42 months)",
  "doorOpeningDoorsOpened54": "Door Opening - Number of doors opened (not forced trials) (54 months)",

  "doorOpeningForcedTrials30": "Door Opening - Number of forced trials (30 months)",
  "doorOpeningForcedTrials36": "Door Opening - Number of forced trials (36 months)",
  "doorOpeningForcedTrials42": "Door Opening - Number of forced trials (42 months)",
  "doorOpeningForcedTrials54": "Door Opening - Number of forced trials (54 months)",

  "doorOpeningDelaysAfterPunishment30": "Door Opening - Number of delays after a punishment (30 months)",
  "doorOpeningDelaysAfterPunishment36": "Door Opening - Number of delays after a punishment (36 months)",
  "doorOpeningDelaysAfterPunishment42": "Door Opening - Number of delays after a punishment (42 months)",
  "doorOpeningDelaysAfterPunishment54": "Door Opening - Number of delays after a punishment (54 months)",

  "doorOpeningDelaysAfterReward30": "Door Opening - Number of delays after a reward (30 months)",
  "doorOpeningDelaysAfterReward36": "Door Opening - Number of delays after a reward (36 months)",
  "doorOpeningDelaysAfterReward42": "Door Opening - Number of delays after a reward (42 months)",
  "doorOpeningDelaysAfterReward54": "Door Opening - Number of delays after a reward (54 months)",

  "doorOpeningDelayOfFirstTrial30": "Door Opening - Was there a delay on the first trial? (30 months)",
  "doorOpeningDelayOfFirstTrial36": "Door Opening - Was there a delay on the first trial? (36 months)",
  "doorOpeningDelayOfFirstTrial42": "Door Opening - Was there a delay on the first trial? (42 months)",
  "doorOpeningDelayOfFirstTrial54": "Door Opening - Was there a delay on the first trial? (54 months)",

  "doorOpeningComposite30": "Mean of doors opened and reversed forced trials (30 months)",
  "doorOpeningComposite36": "Mean of doors opened and reversed forced trials (36 months)",
  "doorOpeningComposite42": "Mean of doors opened and reversed forced trials (42 months)",
  "doorOpeningComposite54": "Mean of doors opened and reversed forced trials (54 months)",

  "doorOpeningRewardSensitivity30": "Sensitivity to reward; positive deviations above optimal doors opened (30 months)",
  "doorOpeningRewardSensitivity36": "Sensitivity to reward; positive deviations above optimal doors opened (36 months)",
  "doorOpeningRewardSensitivity42": "Sensitivity to reward; positive deviations above optimal doors opened (42 months)",
  "doorOpeningRewardSensitivity54": "Sensitivity to reward; positive deviations above optimal doors opened (54 months)",

  "doorOpeningPunishmentSensitivity30": "Sensitivity to punishment; negative deviations below optimal doors opened (30 months)",
  "doorOpeningPunishmentSensitivity36": "Sensitivity to punishment; negative deviations below optimal doors opened (36 months)",
  "doorOpeningPunishmentSensitivity42": "Sensitivity to punishment; negative deviations below optimal doors opened (42 months)",
  "doorOpeningPunishmentSensitivity54": "Sensitivity to punishment; negative deviations below optimal doors opened (54 months)",

  "fruitStroopChildPres30": "Fruit Stroop - Other child present? (30 months)",
  "fruitStroopChildPres36": "Fruit Stroop - Other child present? (36 months)",
  "fruitStroopChildPres42": "Fruit Stroop - Other child present? (42 months)",
  "fruitStroopChildPres54": "Fruit Stroop - Other child present? (54 months)",

  "fruitStroopParentPres30": "Fruit Stroop - Parent Present? (30 months)",
  "fruitStroopParentPres36": "Fruit Stroop - Parent Present? (36 months)",
  "fruitStroopParentPres42": "Fruit Stroop - Parent Present? (42 months)",
  "fruitStroopParentPres54": "Fruit Stroop - Parent Present? (54 months)",

  "fruitStroopSmall30": "Small fruit score (30 months)",
  "fruitStroopSmall36": "Small fruit score (36 months)",
  "fruitStroopSmall42": "Small fruit score (42 months)",
  "fruitStroopSmall54": "Small fruit score (54 months)",

  "fruitStroopLarge30": "Large fruit score (30 months)",
  "fruitStroopLarge36": "Large fruit score (36 months)",
  "fruitStroopLarge42": "Large fruit score (42 months)",
  "fruitStroopLarge54": "Large fruit score (54 months)",

  "fruitStroopAvg30": "Average of small & large fruit trials (30 months)",
  "fruitStroopAvg36": "Average of small & large fruit trials (36 months)",
  "fruitStroopAvg42": "Average of small & large fruit trials (42 months)",
  "fruitStroopAvg54": "Average of small & large fruit trials (54 months)",

  "complimentsChildPresent30": "Compliments - Other Child Present? (30 months)",
  "complimentsChildPresent36": "Compliments - Other Child Present? (36 months)",
  "complimentsChildPresent42": "Compliments - Other Child Present? (42 months)",
  "complimentsChildPresent54": "Compliments - Other Child Present? (54 months)",

  "complimentsParentPresent30": "Compliments - Parent Present? (30 months)",
  "complimentsParentPresent36": "Compliments - Parent Present? (36 months)",
  "complimentsParentPresent42": "Compliments - Parent Present? (42 months)",
  "complimentsParentPresent54": "Compliments - Parent Present? (54 months)",

  "complimentsEmbarrassment30": "Did the child show any signs of embarrassment? (all 3 behaviors present) (30 months)",
  "complimentsEmbarrassment36": "Did the child show any signs of embarrassment? (all 3 behaviors present) (36 months)",
  "complimentsEmbarrassment42": "Did the child show any signs of embarrassment? (all 3 behaviors present) (42 months)",
  "complimentsEmbarrassment54": "Did the child show any signs of embarrassment? (all 3 behaviors present) (54 months)",

  "complimentsShame30": "Did the child show any signs of shame? (3 of 5 behaviors present) (30 months)",
  "complimentsShame36": "Did the child show any signs of shame? (3 of 5 behaviors present) (36 months)",
  "complimentsShame42": "Did the child show any signs of shame? (3 of 5 behaviors present) (42 months)",
  "complimentsShame54": "Did the child show any signs of shame? (3 of 5 behaviors present) (54 months)",

  "complimentsPride30": "Did the child show any signs of pride? (3 of 5 behaviors present) (30 months)",
  "complimentsPride36": "Did the child show any signs of pride? (3 of 5 behaviors present) (36 months)",
  "complimentsPride42": "Did the child show any signs of pride? (3 of 5 behaviors present) (42 months)",
  "complimentsPride54": "Did the child show any signs of pride? (3 of 5 behaviors present) (54 months)",

  "complimentsSelfAwareness30": "Mean of Embarrassment, Shame, and Pride (30 months)",
  "complimentsSelfAwareness36": "Mean of Embarrassment, Shame, and Pride (36 months)",
  "complimentsSelfAwareness42": "Mean of Embarrassment, Shame, and Pride (42 months)",
  "complimentsSelfAwareness54": "Mean of Embarrassment, Shame, and Pride (54 months)",

  "grassSnowChildPresent30": "Grass Snow - Other Child Present? (30 months)",
  "grassSnowChildPresent36": "Grass Snow - Other Child Present? (36 months)",
  "grassSnowChildPresent42": "Grass Snow - Other Child Present? (42 months)",
  "grassSnowChildPresent54": "Grass Snow - Other Child Present? (54 months)",

  "grassSnowParentPresent30": "Grass Snow - Parent Present? (30 months)",
  "grassSnowParentPresent36": "Grass Snow - Parent Present? (36 months)",
  "grassSnowParentPresent42": "Grass Snow - Parent Present? (42 months)",
  "grassSnowParentPresent54": "Grass Snow - Parent Present? (54 months)",

  "grassSnowTotal30": "Sum of all Grass Snow trial scores across 14 trials (30 months)",
  "grassSnowTotal36": "Sum of all Grass Snow trial scores across 14 trials (36 months)",
  "grassSnowTotal42": "Sum of all Grass Snow trial scores across 14 trials (42 months)",
  "grassSnowTotal54": "Sum of all Grass Snow trial scores across 14 trials (54 months)",

  "grassSnowAvg30": "Average score across Grass Snow trials (30 months)",
  "grassSnowAvg36": "Average score across Grass Snow trials (36 months)",
  "grassSnowAvg42": "Average score across Grass Snow trials (42 months)",
  "grassSnowAvg54": "Average score across Grass Snow trials (54 months)",

  "giftDelayLatency30": "Latency mean; mean of latency variables (30 months)",
  "giftDelayLatency36": "Latency mean; mean of latency variables (36 months)",
  "giftDelayLatency42": "Latency mean; mean of latency variables (42 months)",
  "giftDelayLatency54": "Latency mean; mean of latency variables (54 months)",

  "giftDelayScore30": "Gift Delay overall composite score (30 months)",
  "giftDelayScore36": "Gift Delay overall composite score (36 months)",
  "giftDelayScore42": "Gift Delay overall composite score (42 months)",
  "giftDelayScore54": "Gift Delay overall composite score (54 months)",

  "giftDelayLatencyToTouchBag30": "Gift Delay - Latency before first instance of touching bag (seconds) (30 months)",
  "giftDelayLatencyToTouchBag36": "Gift Delay - Latency before first instance of touching bag (seconds) (36 months)",
  "giftDelayLatencyToTouchBag42": "Gift Delay - Latency before first instance of touching bag (seconds) (42 months)",
  "giftDelayLatencyToTouchBag54": "Gift Delay - Latency before first instance of touching bag (seconds) (54 months)",

  "giftDelayLatencyToOpenBag30": "Gift Delay - Latency before first instance of opening/peeking in bag (seconds) (30 months)",
  "giftDelayLatencyToOpenBag36": "Gift Delay - Latency before first instance of opening/peeking in bag (seconds) (36 months)",
  "giftDelayLatencyToOpenBag42": "Gift Delay - Latency before first instance of opening/peeking in bag (seconds) (42 months)",
  "giftDelayLatencyToOpenBag54": "Gift Delay - Latency before first instance of opening/peeking in bag (seconds) (54 months)",

  "giftDelayLatencyToHandInBag30": "Gift Delay - Latency before first instance of putting hand in bag (seconds) (30 months)",
  "giftDelayLatencyToHandInBag36": "Gift Delay - Latency before first instance of putting hand in bag (seconds) (36 months)",
  "giftDelayLatencyToHandInBag42": "Gift Delay - Latency before first instance of putting hand in bag (seconds) (42 months)",
  "giftDelayLatencyToHandInBag54": "Gift Delay - Latency before first instance of putting hand in bag (seconds) (54 months)",

  "giftDelayLatencyToPullGiftFromBag30": "Gift Delay - Latency before first instance of pulling gift from bag (seconds) (30 months)",
  "giftDelayLatencyToPullGiftFromBag36": "Gift Delay - Latency before first instance of pulling gift from bag (seconds) (36 months)",
  "giftDelayLatencyToPullGiftFromBag42": "Gift Delay - Latency before first instance of pulling gift from bag (seconds) (42 months)",
  "giftDelayLatencyToPullGiftFromBag54": "Gift Delay - Latency before first instance of pulling gift from bag (seconds) (54 months)",

  "brokenToyChildPresent30": "Broken Toy - Other Child Present? (30 months)",
  "brokenToyParentPresent30": "Broken Toy - Parent Present? (30 months)",
  "brokenToyDistress30": "Child distress immediately after the toy broke (30 months)",
  "brokenToyComprehension30": "Comprehension of another's distress after the experimenter says \"uh oh!\" and \"what happened?\" (30 months)",
  "brokenToyProsocial30": "Prosocial behavior (solutions offered to fix the broken toy) (30 months)",
  "brokenToyAveDistress30": "Mean of distress and comprehension",

  "brokenToyChildPresent36": "Broken Toy - Other Child Present? (36 months)",
  "brokenToyParentPresent36": "Broken Toy - Parent Present? (36 months)",
  "brokenToyDistress36": "Child distress immediately after the toy broke (36 months)",
  "brokenToyComprehension36": "Comprehension of another's distress after the experimenter says \"uh oh!\" and \"what happened?\" (36 months)",
  "brokenToyProsocial36": "Prosocial behavior (solutions offered to fix the broken toy) (36 months)",
  "brokenToyAveDistress36": "Mean of distress and comprehension",

  "brokenToyChildPresent42": "Broken Toy - Other Child Present? (42 months)",
  "brokenToyParentPresent42": "Broken Toy - Parent Present? (42 months)",
  "brokenToyDistress42": "Child distress immediately after the toy broke (42 months)",
  "brokenToyComprehension42": "Comprehension of another's distress after the experimenter says \"uh oh!\" and \"what happened?\" (42 months)",
  "brokenToyProsocial42": "Prosocial behavior (solutions offered to fix the broken toy) (42 months)",
  "brokenToyAveDistress42": "Mean of distress and comprehension",

  "brokenToyChildPresent54": "Broken Toy - Other Child Present? (54 months)",
  "brokenToyParentPresent54": "Broken Toy - Parent Present? (54 months)",
  "brokenToyDistress54": "Child distress immediately after the toy broke (54 months)",
  "brokenToyComprehension54": "Comprehension of another's distress after the experimenter says \"uh oh!\" and \"what happened?\" (54 months)",
  "brokenToyProsocial54": "Prosocial behavior (solutions offered to fix the broken toy) (54 months)",
  "brokenToyAveDistress54": "Mean of distress and comprehension",

  "parentalControlFreePlayChildPres30": "Parental Control Free Play - Other Child Present? (30 months)",
  "parentalControlFreePlayNoInvolvementP30": "Proportion of coded intervals with no involvement during Free Play (30 months)",
  "parentalControlFreePlayVisualContactOnlyP30": "Proportion of coded intervals with visual contact only during Free Play (30 months)",
  "parentalControlFreePlaySocialExchangeP30": "Proportion of coded intervals with social exchange during Free Play (30 months)",
  "parentalControlFreePlaySocialExchangePhysicalP30": "Proportion of coded intervals with social exchange & physical contact during Free Play (30 months)",
  "parentalControlFreePlayGentleControlP30": "Proportion of coded intervals with guidance/gentle control during Free Play (30 months)",
  "parentalControlFreePlayGentleControlPhysicalP30": "Proportion of coded intervals with guidance/gentle control & physical contact during Free Play (30 months)",
  "parentalControlFreePlayNegativeControlP30": "Proportion of coded intervals with negative control during Free Play (30 months)",
  "parentalControlFreePlayNegativeControlPhysicalP30": "Proportion of coded intervals with negative control & physical contact during Free Play (30 months)",

  "parentalControlPhoneCallChildPres30": "Parental Control Phone Call - Other Child Present? (30 months)",
  "parentalControlPhoneCallNoInvolvementP30": "Proportion of coded intervals with no involvement during Phone Call task (30 months)",
  "parentalControlPhoneCallVisualContactOnlyP30": "Proportion of coded intervals with visual contact only during Phone Call task (30 months)",
  "parentalControlPhoneCallSocialExchangeP30": "Proportion of coded intervals with social exchange during Phone Call task (30 months)",
  "parentalControlPhoneCallSocialExchangePhysicalP30": "Proportion of coded intervals with social exchange & physical contact during Phone Call task (30 months)",
  "parentalControlPhoneCallGentleControlP30": "Proportion of coded intervals with guidance/gentle control during Phone Call task (30 months)",
  "parentalControlPhoneCallGentleControlPhysicalP30": "Proportion of coded intervals with guidance/gentle control & physical contact during Phone Call task (30 months)",
  "parentalControlPhoneCallNegativeControlP30": "Proportion of coded intervals with negative control during Phone Call task (30 months)",
  "parentalControlPhoneCallNegativeControlPhysicalP30": "Proportion of coded intervals with negative control & physical contact during Phone Call task (30 months)",

  "parentalControlToyCleanupChildPres30": "Parental Control Toy Cleanup - Other Child Present? (30 months)",
  "parentalControlToyCleanupNoInvolvementP30": "Proportion of coded intervals with no involvement during Toy Cleanup task (30 months)",
  "parentalControlToyCleanupVisualContactOnlyP30": "Proportion of coded intervals with visual contact only during Toy Cleanup task (30 months)",
  "parentalControlToyCleanupSocialExchangeP30": "Proportion of coded intervals with social exchange during Toy Cleanup task (30 months)",
  "parentalControlToyCleanupSocialExchangePhysicalP30": "Proportion of coded intervals with social exchange & physical contact during Toy Cleanup task (30 months)",
  "parentalControlToyCleanupGentleControlP30": "Proportion of coded intervals with guidance/gentle control during Toy Cleanup task (30 months)",
  "parentalControlToyCleanupGentleControlPhysicalP30": "Proportion of coded intervals with guidance/gentle control & physical contact during Toy Cleanup task (30 months)",
  "parentalControlToyCleanupNegativeControlP30": "Proportion of coded intervals with negative control during Toy Cleanup task (30 months)",
  "parentalControlToyCleanupNegativeControlPhysicalP30": "Proportion of coded intervals with negative control & physical contact during Toy Cleanup task (30 months)",

  "tokenSortChildPres30": "Token Sort - Other Child Present? (30 months)",
  "tokenSortParentPres30": "Token Sort - Parent Present? (30 months)",
  "tokenSortTimeSorting30": "Token Sort - Amount of time child sorts tokens (30 months)",

  "tokenSortChildPres36": "Token Sort - Other Child Present? (36 months)",
  "tokenSortParentPres36": "Token Sort - Parent Present? (36 months)",
  "tokenSortTimeSorting36": "Token Sort - Amount of time child sorts tokens (36 months)",

  "tokenSortChildPres42": "Token Sort - Other Child Present? (42 months)",
  "tokenSortParentPres42": "Token Sort - Parent Present? (42 months)",
  "tokenSortTimeSorting42": "Token Sort - Amount of time child sorts tokens (42 months)",

  "tokenSortChildPres54": "Token Sort - Other Child Present? (54 months)",
  "tokenSortParentPres54": "Token Sort - Parent Present? (54 months)",
  "tokenSortTimeSorting54": "Token Sort - Amount of time child sorts tokens (54 months)",

  "toyFrustrationChildPres30": "Toy Frustration - Other Child Present? (30 months)",
  "toyFrustrationParentPres30": "Toy Frustration - Parent Present? (30 months)",

  "toyFrustrationChildPres36": "Toy Frustration - Other Child Present? (36 months)",
  "toyFrustrationParentPres36": "Toy Frustration - Parent Present? (36 months)",

  "toyFrustrationChildPres42": "Toy Frustration - Other Child Present? (42 months)",
  "toyFrustrationParentPres42": "Toy Frustration - Parent Present? (42 months)",

  "toyFrustrationChildPres54": "Toy Frustration - Other Child Present? (54 months)",
  "toyFrustrationParentPres54": "Toy Frustration - Parent Present? (54 months)",

  "walkALineChildPres30": "Walk A Line - Other Child Present? (30 months)",
  "walkALineParentPres30": "Walk A Line - Parent Present? (30 months)",

  "walkALineChildPres36": "Walk A Line - Other Child Present? (36 months)",
  "walkALineParentPres36": "Walk A Line - Parent Present? (36 months)",

  "walkALineChildPres42": "Walk A Line - Other Child Present? (42 months)",
  "walkALineParentPres42": "Walk A Line - Parent Present? (42 months)",

  "walkALineChildPres54": "Walk A Line - Other Child Present? (54 months)",
  "walkALineParentPres54": "Walk A Line - Parent Present? (54 months)",

  "walkALineTrial1Baseline30": "Walk A Line - Time Trial 1 (30 months)",
  "walkALineTrail2Slow30": "Walk A Line - Time Trial 2 (30 months)",
  "walkALineTrail3Slow30": "Walk A Line - Time Trial 3 (30 months)",

  "walkALineTrial1Baseline36": "Walk A Line - Time Trial 1 (36 months)",
  "walkALineTrail2Slow36": "Walk A Line - Time Trial 2 (36 months)",
  "walkALineTrail3Slow36": "Walk A Line - Time Trial 3 (36 months)",

  "walkALineTrial1Baseline42": "Walk A Line - Time Trial 1 (42 months)",
  "walkALineTrail2Slow42": "Walk A Line - Time Trial 2 (42 months)",
  "walkALineTrail3Slow42": "Walk A Line - Time Trial 3 (42 months)",

  "walkALineTrial1Baseline54": "Walk A Line - Time Trial 1 (54 months)",
  "walkALineTrail2Slow54": "Walk A Line - Time Trial 2 (54 months)",
  "walkALineTrail3Slow54": "Walk A Line - Time Trial 3 (54 months)",

  "walkALineSlow30": "Average of slow trials (30 months)",
  "walkALineSlowMinusBaseline30": "Time difference between slow trials and baseline trial (30 months)",
  "walkALineRatioBaselineOverSlow30": "Time ratio of baseline trial by slow trials (30 months)",

  "walkALineSlow36": "Average of slow trials (36 months)",
  "walkALineSlowMinusBaseline36": "Time difference between slow trials and baseline trial (36 months)",
  "walkALineRatioBaselineOverSlow36": "Time ratio of baseline trial by slow trials (36 months)",

  "walkALineSlow42": "Average of slow trials (42 months)",
  "walkALineSlowMinusBaseline42": "Time difference between slow trials and baseline trial (42 months)",
  "walkALineRatioBaselineOverSlow42": "Time ratio of baseline trial by slow trials (42 months)",

  "walkALineSlow54": "Average of slow trials (54 months)",
  "walkALineSlowMinusBaseline54": "Time difference between slow trials and baseline trial (54 months)",
  "walkALineRatioBaselineOverSlow54": "Time ratio of baseline trial by slow trials (54 months)",

  "whisperGameChildPres30": "Whisper Game - Other Child Present? (30 months)",
  "whisperGameParentPres30": "Whisper Game - Parent Present? (30 months)",

  "whisperGameChildPres36": "Whisper Game - Other Child Present? (36 months)",
  "whisperGameParentPres36": "Whisper Game - Parent Present? (36 months)",

  "whisperGameChildPres42": "Whisper Game - Other Child Present? (42 months)",
  "whisperGameParentPres42": "Whisper Game - Parent Present? (42 months)",

  "whisperGameChildPres54": "Whisper Game - Other Child Present? (54 months)",
  "whisperGameParentPres54": "Whisper Game - Parent Present? (54 months)",

  "whisperGame_WinniePooh30": "Whisper Game - Winnie the Pooh Score (30 months)",
  "whisperGame_MickeyMouse30": "Whisper Game - Mickey Mouse Score (30 months)",
  "whisperGame_Ernie30": "Whisper Game - Ernie Score (30 months)",
  "whisperGame_BigBird30": "Whisper Game - Big Bird Score (30 months)",
  "whisperGame_Piglet30": "Whisper Game - Piglet Score (30 months)",
  "whisperGame_CookieMonster30": "Whisper Game - Cookie Monster Score (30 months)",
  "whisperGame_Eeyore30": "Whisper Game - Eeyore Score (30 months)",
  "whisperGame_Bert30": "Whisper Game - Bert Score (30 months)",
  "whisperGame_Tigger30": "Whisper Game - Tigger Score (30 months)",
  "whisperGame_Barney30": "Whisper Game - Barney Score (30 months)",
  "whisperGame_Elmo30": "Whisper Game - Elmo Score (30 months)",
  "whisperGame_MinnieMouse30": "Whisper Game - Minnie Mouse Score (30 months)",

  "whisperGame_WinniePooh36": "Whisper Game - Winnie the Pooh Score (36 months)",
  "whisperGame_MickeyMouse36": "Whisper Game - Mickey Mouse Score (36 months)",
  "whisperGame_Ernie36": "Whisper Game - Ernie Score (36 months)",
  "whisperGame_BigBird36": "Whisper Game - Big Bird Score (36 months)",
  "whisperGame_Piglet36": "Whisper Game - Piglet Score (36 months)",
  "whisperGame_CookieMonster36": "Whisper Game - Cookie Monster Score (36 months)",
  "whisperGame_Eeyore36": "Whisper Game - Eeyore Score (36 months)",
  "whisperGame_Bert36": "Whisper Game - Bert Score (36 months)",
  "whisperGame_Tigger36": "Whisper Game - Tigger Score (36 months)",
  "whisperGame_Barney36": "Whisper Game - Barney Score (36 months)",
  "whisperGame_Elmo36": "Whisper Game - Elmo Score (36 months)",
  "whisperGame_MinnieMouse36": "Whisper Game - Minnie Mouse Score (36 months)",

  "whisperGame_WinniePooh42": "Whisper Game - Winnie the Pooh Score (42 months)",
  "whisperGame_MickeyMouse42": "Whisper Game - Mickey Mouse Score (42 months)",
  "whisperGame_Ernie42": "Whisper Game - Ernie Score (42 months)",
  "whisperGame_BigBird42": "Whisper Game - Big Bird Score (42 months)",
  "whisperGame_Piglet42": "Whisper Game - Piglet Score (42 months)",
  "whisperGame_CookieMonster42": "Whisper Game - Cookie Monster Score (42 months)",
  "whisperGame_Eeyore42": "Whisper Game - Eeyore Score (42 months)",
  "whisperGame_Bert42": "Whisper Game - Bert Score (42 months)",
  "whisperGame_Tigger42": "Whisper Game - Tigger Score (42 months)",
  "whisperGame_Barney42": "Whisper Game - Barney Score (42 months)",
  "whisperGame_Elmo42": "Whisper Game - Elmo Score (42 months)",
  "whisperGame_MinnieMouse42": "Whisper Game - Minnie Mouse Score (42 months)",

  "whisperGame_WinniePooh54": "Whisper Game - Winnie the Pooh Score (54 months)",
  "whisperGame_MickeyMouse54": "Whisper Game - Mickey Mouse Score (54 months)",
  "whisperGame_Ernie54": "Whisper Game - Ernie Score (54 months)",
  "whisperGame_BigBird54": "Whisper Game - Big Bird Score (54 months)",
  "whisperGame_Piglet54": "Whisper Game - Piglet Score (54 months)",
  "whisperGame_CookieMonster54": "Whisper Game - Cookie Monster Score (54 months)",
  "whisperGame_Eeyore54": "Whisper Game - Eeyore Score (54 months)",
  "whisperGame_Bert54": "Whisper Game - Bert Score (54 months)",
  "whisperGame_Tigger54": "Whisper Game - Tigger Score (54 months)",
  "whisperGame_Barney54": "Whisper Game - Barney Score (54 months)",
  "whisperGame_Elmo54": "Whisper Game - Elmo Score (54 months)",
  "whisperGame_MinnieMouse54": "Whisper Game - Minnie Mouse Score (54 months)",

  "whisperGameTotal30": "Whisper game total score (30 months)",
  "whisperGameAvg30": "Whisper game average score (30 months)",

  "whisperGameTotal36": "Whisper game total score (36 months)",
  "whisperGameAvg36": "Whisper game average score (36 months)",

  "whisperGameTotal42": "Whisper game total score (42 months)",
  "whisperGameAvg42": "Whisper game average score (42 months)",

  "whisperGameTotal54": "Whisper game total score (54 months)",
  "whisperGameAvg54": "Whisper game average score (54 months)",

  "childNegativeToyCleanupChildPres30": "Child Negative Toy Clean-up - Other Child Present? (30 months)",
  "childNegativeToyCleanUpNegativeAffect30": "Weighted negative affect score during Toy Clean-up",
  "childNegativeToyCleanUpNoNegativeP30": "Proportion of coded intervals with no negative affect during Toy Clean-up",
  "childNegativeToyCleanUpNegativeP30": "Proportion of coded intervals with negative affect during Toy Clean-up",
  "childNegativeToyCleanUpHiNegativeP30": "Proportion of coded intervals with high negative affect during Toy Clean-up",
  "childNegativeToyProhibitionChildPres30": "Child Negative Toy Prohibition - Other Child Present? (30 months)",
  "childNegativeToyProhibitionNegativeAffect30": "Weighted negative affect score during Toy Prohibition",
  "childNegativeToyProhibitionNoNegativeP30": "Proportion of coded intervals with no negative affect during Toy Prohibition",
  "childNegativeToyProhibitionNegativeP30": "Proportion of coded intervals with negative affect during Toy Prohibition",
  "childNegativeToyProhibitionHiNegativeP30": "Proportion of coded intervals with high negative affect during Toy Prohibition",

  "childNegativeToyCleanupChildPres36": "Child Negative Toy Clean-up - Other Child Present? (36 months)",
  "childNegativeToyCleanUpNegativeAffect36": "Weighted negative affect score during Toy Clean-up",
  "childNegativeToyCleanUpNoNegativeP36": "Proportion of coded intervals with no negative affect during Toy Clean-up",
  "childNegativeToyCleanUpNegativeP36": "Proportion of coded intervals with negative affect during Toy Clean-up",
  "childNegativeToyCleanUpHiNegativeP36": "Proportion of coded intervals with high negative affect during Toy Clean-up",
  "childNegativeToyProhibitionChildPres36": "Child Negative Toy Prohibition - Other Child Present? (36 months)",
  "childNegativeToyProhibitionNegativeAffect36": "Weighted negative affect score during Toy Prohibition",
  "childNegativeToyProhibitionNoNegativeP36": "Proportion of coded intervals with no negative affect during Toy Prohibition",
  "childNegativeToyProhibitionNegativeP36": "Proportion of coded intervals with negative affect during Toy Prohibition",
  "childNegativeToyProhibitionHiNegativeP36": "Proportion of coded intervals with high negative affect during Toy Prohibition",

  "childNegativeToyCleanupChildPres42": "Child Negative Toy Clean-up - Other Child Present? (42 months)",
  "childNegativeToyCleanUpNegativeAffect42": "Weighted negative affect score during Toy Clean-up",
  "childNegativeToyCleanUpNoNegativeP42": "Proportion of coded intervals with no negative affect during Toy Clean-up",
  "childNegativeToyCleanUpNegativeP42": "Proportion of coded intervals with negative affect during Toy Clean-up",
  "childNegativeToyCleanUpHiNegativeP42": "Proportion of coded intervals with high negative affect during Toy Clean-up",
  "childNegativeToyProhibitionChildPres42": "Child Negative Toy Prohibition - Other Child Present? (42 months)",
  "childNegativeToyProhibitionNegativeAffect42": "Weighted negative affect score during Toy Prohibition",
  "childNegativeToyProhibitionNoNegativeP42": "Proportion of coded intervals with no negative affect during Toy Prohibition",
  "childNegativeToyProhibitionNegativeP42": "Proportion of coded intervals with negative affect during Toy Prohibition",
  "childNegativeToyProhibitionHiNegativeP42": "Proportion of coded intervals with high negative affect during Toy Prohibition",

  "childNegativeToyCleanupChildPres54": "Child Negative Toy Clean-up - Other Child Present? (54 months)",
  "childNegativeToyCleanUpNegativeAffect54": "Weighted negative affect score during Toy Clean-up",
  "childNegativeToyCleanUpNoNegativeP54": "Proportion of coded intervals with no negative affect during Toy Clean-up",
  "childNegativeToyCleanUpNegativeP54": "Proportion of coded intervals with negative affect during Toy Clean-up",
  "childNegativeToyCleanUpHiNegativeP54": "Proportion of coded intervals with high negative affect during Toy Clean-up",
  "childNegativeToyProhibitionChildPres54": "Child Negative Toy Prohibition - Other Child Present? (54 months)",
  "childNegativeToyProhibitionNegativeAffect54": "Weighted negative affect score during Toy Prohibition",
  "childNegativeToyProhibitionNoNegativeP54": "Proportion of coded intervals with no negative affect during Toy Prohibition",
  "childNegativeToyProhibitionNegativeP54": "Proportion of coded intervals with negative affect during Toy Prohibition",
  "childNegativeToyProhibitionHiNegativeP54": "Proportion of coded intervals with high negative affect during Toy Prohibition",

  "childPositiveToyCleanupChildPres30": "Child Positive Toy Cleanup - Other Child Present? (30 months)",
  "childPositiveToyCleanUpPositiveAffect30": "Weighted positive affect score during Toy Cleanup",
  "childPositiveToyCleanUpNoPositiveP30": "Proportion of intervals with no positive affect during Toy Cleanup",
  "childPositiveToyCleanUpPositiveP30": "Proportion of intervals with positive affect during Toy Cleanup",
  "childPositiveToyCleanUpHiPositiveP30": "Proportion of intervals with high positive affect during Toy Cleanup",
  "childPositiveToyProhibitionChildPres30": "Child Positive Toy Prohibition - Other Child Present? (30 months)",
  "childPositiveToyProhibitionPositiveAffect30": "Weighted positive affect score during Toy Prohibition",
  "childPositiveToyProhibitionNoPositiveP30": "Proportion of intervals with no positive affect during Toy Prohibition",
  "childPositiveToyProhibitionPositiveP30": "Proportion of intervals with positive affect during Toy Prohibition",
  "childPositiveToyProhibitionHiPositiveP30": "Proportion of intervals with high positive affect during Toy Prohibition",

  "childPositiveToyCleanupChildPres36": "Child Positive Toy Cleanup - Other Child Present? (36 months)",
  "childPositiveToyCleanUpPositiveAffect36": "Weighted positive affect score during Toy Cleanup",
  "childPositiveToyCleanUpNoPositiveP36": "Proportion of intervals with no positive affect during Toy Cleanup",
  "childPositiveToyCleanUpPositiveP36": "Proportion of intervals with positive affect during Toy Cleanup",
  "childPositiveToyCleanUpHiPositiveP36": "Proportion of intervals with high positive affect during Toy Cleanup",
  "childPositiveToyProhibitionChildPres36": "Child Positive Toy Prohibition - Other Child Present? (36 months)",
  "childPositiveToyProhibitionPositiveAffect36": "Weighted positive affect score during Toy Prohibition",
  "childPositiveToyProhibitionNoPositiveP36": "Proportion of intervals with no positive affect during Toy Prohibition",
  "childPositiveToyProhibitionPositiveP36": "Proportion of intervals with positive affect during Toy Prohibition",
  "childPositiveToyProhibitionHiPositiveP36": "Proportion of intervals with high positive affect during Toy Prohibition",

  "childPositiveToyCleanupChildPres42": "Child Positive Toy Cleanup - Other Child Present? (42 months)",
  "childPositiveToyCleanUpPositiveAffect42": "Weighted positive affect score during Toy Cleanup",
  "childPositiveToyCleanUpNoPositiveP42": "Proportion of intervals with no positive affect during Toy Cleanup",
  "childPositiveToyCleanUpPositiveP42": "Proportion of intervals with positive affect during Toy Cleanup",
  "childPositiveToyCleanUpHiPositiveP42": "Proportion of intervals with high positive affect during Toy Cleanup",
  "childPositiveToyProhibitionChildPres42": "Child Positive Toy Prohibition - Other Child Present? (42 months)",
  "childPositiveToyProhibitionPositiveAffect42": "Weighted positive affect score during Toy Prohibition",
  "childPositiveToyProhibitionNoPositiveP42": "Proportion of intervals with no positive affect during Toy Prohibition",
  "childPositiveToyProhibitionPositiveP42": "Proportion of intervals with positive affect during Toy Prohibition",
  "childPositiveToyProhibitionHiPositiveP42": "Proportion of intervals with high positive affect during Toy Prohibition",

  "childPositiveToyCleanupChildPres54": "Child Positive Toy Cleanup - Other Child Present? (54 months)",
  "childPositiveToyCleanUpPositiveAffect54": "Weighted positive affect score during Toy Cleanup",
  "childPositiveToyCleanUpNoPositiveP54": "Proportion of intervals with no positive affect during Toy Cleanup",
  "childPositiveToyCleanUpPositiveP54": "Proportion of intervals with positive affect during Toy Cleanup",
  "childPositiveToyCleanUpHiPositiveP54": "Proportion of intervals with high positive affect during Toy Cleanup",
  "childPositiveToyProhibitionChildPres54": "Child Positive Toy Prohibition - Other Child Present? (54 months)",
  "childPositiveToyProhibitionPositiveAffect54": "Weighted positive affect score during Toy Prohibition",
  "childPositiveToyProhibitionNoPositiveP54": "Proportion of intervals with no positive affect during Toy Prohibition",
  "childPositiveToyProhibitionPositiveP54": "Proportion of intervals with positive affect during Toy Prohibition",
  "childPositiveToyProhibitionHiPositiveP54": "Proportion of intervals with high positive affect during Toy Prohibition",

  "snackDelayChildPres30": "Snack Delay - Other Child Present? (30 months)",
  "snackDelayParentPres30": "Snack Delay - Parent Present? (30 months)",

  "snackDelayChildPres36": "Snack Delay - Other Child Present? (36 months)",
  "snackDelayParentPres36": "Snack Delay - Parent Present? (36 months)",

  "snackDelayChildPres42": "Snack Delay - Other Child Present? (42 months)",
  "snackDelayParentPres42": "Snack Delay - Parent Present? (42 months)",

  "snackDelayChildPres54": "Snack Delay - Other Child Present? (54 months)",
  "snackDelayParentPres54": "Snack Delay - Parent Present? (54 months)",

  "snackDelayAvg30": "Mean of all Snack Delay scores across all trials and both parts (30 months)",
  "snackDelayPt1Avg30": "Mean of Part 1 delay scores across trials (Part 1 = time until experimenter touches the bell) (30 months)",
  "snackDelayPt2Avg30": "Mean of Part 2 delay scores across trials (Part 2 = time between experimenter touching and ringing the bell) (30 months)",

  "snackDelayAvg36": "Mean of all Snack Delay scores across all trials and both parts (36 months)",
  "snackDelayPt1Avg36": "Mean of Part 1 delay scores across trials (Part 1 = time until experimenter touches the bell) (36 months)",
  "snackDelayPt2Avg36": "Mean of Part 2 delay scores across trials (Part 2 = time between experimenter touching and ringing the bell) (36 months)",

  "snackDelayAvg42": "Mean of all Snack Delay scores across all trials and both parts (42 months)",
  "snackDelayPt1Avg42": "Mean of Part 1 delay scores across trials (Part 1 = time until experimenter touches the bell) (42 months)",
  "snackDelayPt2Avg42": "Mean of Part 2 delay scores across trials (Part 2 = time between experimenter touching and ringing the bell) (42 months)",

  "snackDelayAvg54": "Mean of all Snack Delay scores across all trials and both parts (54 months)",
  "snackDelayPt1Avg54": "Mean of Part 1 delay scores across trials (Part 1 = time until experimenter touches the bell) (54 months)",
  "snackDelayPt2Avg54": "Mean of Part 2 delay scores across trials (Part 2 = time between experimenter touching and ringing the bell) (54 months)",

  "stopGoChildPres30": "Stop Go - Other Child Present? (30 months)",
  "stopGoParentPres30": "Stop Go - Parent Present? (30 months)",

  "stopGoChildPres36": "Stop Go - Other Child Present? (36 months)",
  "stopGoParentPres36": "Stop Go - Parent Present? (36 months)",

  "stopGoChildPres42": "Stop Go - Other Child Present? (42 months)",
  "stopGoParentPres42": "Stop Go - Parent Present? (42 months)",

  "stopGoChildPres54": "Stop Go - Other Child Present? (54 months)",
  "stopGoParentPres54": "Stop Go - Parent Present? (54 months)",

  "stopGoStopP30": "correct stop = the child immediately stopping in response to the “stop/freeze” command without starting to walk again (30 months)",
  "stopGoRunP30": "run-through = the child completely ignoring the “stop” command (30 months)",
  "stopGoSlowP30": "slow-down = the child slowing down, but not stopping, in response to the stop command (30 months)",
  "stopGoDelayP30": "delay = a time lapse of greater than 1 second between the experimenter’s stop command and the child physically stopping, but stops before reaching the end of the line (30 months)",
  "stopGoAnticipationP30": "anticipation = the child slowing down or hesitating before the stop command (30 months)",
  "stopGoFalseStopP30": "false stop = the child stopping on the line before the experimenter has given the stop command (30 months)",
  "stopGoFalseStartP30": "false start = the child starting after the experimenter has given the stop command but before s/he has given the next “go” command (30 months)",

  "stopGoStopP36": "correct stop = the child immediately stopping in response to the “stop/freeze” command without starting to walk again (36 months)",
  "stopGoRunP36": "run-through = the child completely ignoring the “stop” command (36 months)",
  "stopGoSlowP36": "slow-down = the child slowing down, but not stopping, in response to the stop command. (36 months)",
  "stopGoDelayP36": "delay = a time lapse of greater than 1 second between the experimenter’s stop command and the child physically stopping, but stops before reaching the end of the line (36 months)",
  "stopGoAnticipationP36": "anticipation = the child slowing down or hesitating before the stop command (36 months)",
  "stopGoFalseStopP36": "false stop = the child stopping on the line before the experimenter has given the stop command (36 months)",
  "stopGoFalseStartP36": "false start = the child starting after the experimenter has given the stop command but before s/he has given the next “go” command (36 months)",

  "stopGoStopP42": "correct stop = the child immediately stopping in response to the “stop/freeze” command without starting to walk again (42 months)",
  "stopGoRunP42": "run-through = the child completely ignoring the “stop” command (42 months)",
  "stopGoSlowP42": "slow-down = the child slowing down, but not stopping, in response to the stop command. (42 months)",
  "stopGoDelayP42": "delay = a time lapse of greater than 1 second between the experimenter’s stop command and the child physically stopping, but stops before reaching the end of the line (42 months)",
  "stopGoAnticipationP42": "anticipation = the child slowing down or hesitating before the stop command (42 months)",
  "stopGoFalseStopP42": "false stop = the child stopping on the line before the experimenter has given the stop command (42 months)",
  "stopGoFalseStartP42": "false start = the child starting after the experimenter has given the stop command but before s/he has given the next “go” command (42 months)",

  "stopGoStopP54": "correct stop = the child immediately stopping in response to the “stop/freeze” command without starting to walk again (54 months)",
  "stopGoRunP54": "run-through = the child completely ignoring the “stop” command (54 months)",
  "stopGoSlowP54": "slow-down = the child slowing down, but not stopping, in response to the stop command. (54 months)",
  "stopGoDelayP54": "delay = a time lapse of greater than 1 second between the experimenter’s stop command and the child physically stopping, but stops before reaching the end of the line (54 months)",
  "stopGoAnticipationP54": "anticipation = the child slowing down or hesitating before the stop command (54 months)",
  "stopGoFalseStopP54": "false stop = the child stopping on the line before the experimenter has given the stop command (54 months)",
  "stopGoFalseStartP54": "false start = the child starting after the experimenter has given the stop command but before s/he has given the next “go” command (54 months)",







  "childComplianceToyCleanUpChildPres30": "Child Compliance - Other Child Present? (30 months)",
  "childComplianceToyCleanUpDeviation30": "Deviation composite",
  "childComplianceToyCleanUpNoncompliance30": "Noncompliance composite",
  "childComplianceToyCleanUpDefianceP30": "Proportion of intervals coded as defiance",
  "childComplianceToyCleanUpRefusalOrNegotiationP30": "Proportion of intervals coded as refusal/negotiation",
  "childComplianceToyCleanUpPassiveNonComplianceP30": "Proportion of intervals coded as passive noncompliance",
  "childComplianceToyCleanUpSituationalComplianceP30": "Proportion of intervals coded as situational compliance",
  "childComplianceToyCleanUpCommittedComplianceP30": "Proportion of intervals coded as committed compliance",
  "childComplianceToyCleanUpOtherP30": "Proportion of intervals coded as other",

  "childComplianceToyCleanUpChildPres36": "Child Compliance - Other Child Present? (36 months)",
  "childComplianceToyCleanUpDeviation36": "Deviation composite",
  "childComplianceToyCleanUpNoncompliance36": "Noncompliance composite",
  "childComplianceToyCleanUpDefianceP36": "Proportion of intervals coded as defiance",
  "childComplianceToyCleanUpRefusalOrNegotiationP36": "Proportion of intervals coded as refusal/negotiation",
  "childComplianceToyCleanUpPassiveNonComplianceP36": "Proportion of intervals coded as passive noncompliance",
  "childComplianceToyCleanUpSituationalComplianceP36": "Proportion of intervals coded as situational compliance",
  "childComplianceToyCleanUpCommittedComplianceP36": "Proportion of intervals coded as committed compliance",
  "childComplianceToyCleanUpOtherP36": "Proportion of intervals coded as other",

  "childComplianceToyCleanUpChildPres42": "Child Compliance - Other Child Present? (42 months)",
  "childComplianceToyCleanUpDeviation42": "Deviation composite",
  "childComplianceToyCleanUpNoncompliance42": "Noncompliance composite",
  "childComplianceToyCleanUpDefianceP42": "Proportion of intervals coded as defiance",
  "childComplianceToyCleanUpRefusalOrNegotiationP42": "Proportion of intervals coded as refusal/negotiation",
  "childComplianceToyCleanUpPassiveNonComplianceP42": "Proportion of intervals coded as passive noncompliance",
  "childComplianceToyCleanUpSituationalComplianceP42": "Proportion of intervals coded as situational compliance",
  "childComplianceToyCleanUpCommittedComplianceP42": "Proportion of intervals coded as committed compliance",
  "childComplianceToyCleanUpOtherP42": "Proportion of intervals coded as other",

  "childComplianceToyCleanUpChildPres54": "Child Compliance - Other Child Present? (54 months)",
  "childComplianceToyCleanUpDeviation54": "Deviation composite",
  "childComplianceToyCleanUpNoncompliance54": "Noncompliance composite",
  "childComplianceToyCleanUpDefianceP54": "Proportion of intervals coded as defiance",
  "childComplianceToyCleanUpRefusalOrNegotiationP54": "Proportion of intervals coded as refusal/negotiation",
  "childComplianceToyCleanUpPassiveNonComplianceP54": "Proportion of intervals coded as passive noncompliance",
  "childComplianceToyCleanUpSituationalComplianceP54": "Proportion of intervals coded as situational compliance",
  "childComplianceToyCleanUpCommittedComplianceP54": "Proportion of intervals coded as committed compliance",
  "childComplianceToyCleanUpOtherP54": "Proportion of intervals coded as other",


  "sustainedAttentionProportionTime30": "Mean of proportion time eyes on score, settled score, focused score (30 months)",
  "sustainedAttentionLatency30": "Mean of latency to first eyeson, settled, and focused (30 months)",
  "sustainedAttentionComposite30": "Mean of proportion time z, latency rz, and longest duration z (30 months)",
  "sustainedAttentionProportionTimeLatency30": "Mean of proportion time z and latency rz (30 months)",
  "sustainedAttentionProportionTimeFocused30": "total time focused/total task duration (30 months)",
  "sustainedAttentionProportionTimeSettled30": "total time settled/total task duration (30 months)",

  "sustainedAttentionProportionTime36": "Mean of proportion time eyes on score, settled score, focused score (36 months)",
  "sustainedAttentionLatency36": "Mean of latency to first eyeson, settled, and focused (36 months)",
  "sustainedAttentionComposite36": "Mean of proportion time z, latency rz, and longest duration z (36 months)",
  "sustainedAttentionProportionTimeLatency36": "Mean of proportion time z and latency rz (36 months)",
  "sustainedAttentionProportionTimeFocused36": "total time focused/total task duration (36 months)",
  "sustainedAttentionProportionTimeSettled36": "total time settled/total task duration (36 months)",

  "sustainedAttentionProportionTime42": "Mean of proportion time eyes on score, settled score, focused score (42 months)",
  "sustainedAttentionLatency42": "Mean of latency to first eyeson, settled, and focused (42 months)",
  "sustainedAttentionComposite42": "Mean of proportion time z, latency rz, and longest duration z (42 months)",
  "sustainedAttentionProportionTimeLatency42": "Mean of proportion time z and latency rz (42 months)",
  "sustainedAttentionProportionTimeFocused42": "total time focused/total task duration (42 months)",
  "sustainedAttentionProportionTimeSettled42": "total time settled/total task duration (42 months)",

  "sustainedAttentionProportionTime54": "Mean of proportion time eyes on score, settled score, focused score (54 months)",
  "sustainedAttentionLatency54": "Mean of latency to first eyeson, settled, and focused (54 months)",
  "sustainedAttentionComposite54": "Mean of proportion time z, latency rz, and longest duration z (54 months)",
  "sustainedAttentionProportionTimeLatency54": "Mean of proportion time z and latency rz (54 months)",
  "sustainedAttentionProportionTimeFocused54": "total time focused/total task duration (54 months)",
  "sustainedAttentionProportionTimeSettled54": "total time settled/total task duration (54 months)",


  "parentPositiveFreePlayChildPres30": "Parent Positive Free Play - Other Child Present?",
  "parentPositiveFreePlayIntervals30": "Parent Positive Free Play - Total Number of Intervals",
  "parentPositivePhoneCallChildPres30": "Parent Positive Phone Call - Other Child Present?",
  "parentPositivePhoneCallIntervals30": "Parent Positive Phone Call - Total Number of Intervals",
  "parentPositiveToyCleanupChildPres30": "Parent Positive Toy Cleanup - Other Child Present?",
  "parentPositiveToyCleanupIntervals30": "Parent Positive Toy Cleanup - Total Number of Intervals",
  "parentPositiveFreePlayPositiveAffect30": "Weighted parent positive affect score during Free Play",
  "parentPositiveFreePlayNoPositiveP30": "Proportion of intervals with no positive affect during Free Play",
  "parentPositiveFreePlayPositiveP30": "Proportion of intervals with positive affect during Free Play",
  "parentPositiveFreePlayHiPositiveP30": "Proportion of intervals with high positive affect during Free Play",
  "parentPositivePhoneCallPositiveAffect30": "Weighted parent positive affect score during Phone Call",
  "parentPositivePhoneCallNoPositiveP30": "Proportion of intervals with no positive affect during Phone Call",
  "parentPositivePhoneCallPositiveP30": "Proportion of intervals with positive affect during Phone Call",
  "parentPositivePhoneCallHiPositiveP30": "Proportion of intervals with high positive affect during Phone Call",
  "parentPositiveToyCleanUpPositiveAffect30": "Weighted parent positive affect score during Toy Cleanup",
  "parentPositiveToyCleanUpNoPositiveP30": "Proportion of intervals with no positive affect during Toy Cleanup",
  "parentPositiveToyCleanUpPositiveP30": "Proportion of intervals with positive affect during Toy Cleanup",
  "parentPositiveToyCleanUpHiPositiveP30": "Proportion of intervals with high positive affect during Toy Cleanup",

  "parentPositiveFreePlayChildPres36": "Parent Positive Free Play - Other Child Present?",
  "parentPositiveFreePlayIntervals36": "Parent Positive Free Play - Total Number of Intervals",
  "parentPositivePhoneCallChildPres36": "Parent Positive Phone Call - Other Child Present?",
  "parentPositivePhoneCallIntervals36": "Parent Positive Phone Call - Total Number of Intervals",
  "parentPositiveToyCleanupChildPres36": "Parent Positive Toy Cleanup - Other Child Present?",
  "parentPositiveToyCleanupIntervals36": "Parent Positive Toy Cleanup - Total Number of Intervals",
  "parentPositiveFreePlayPositiveAffect36": "Weighted parent positive affect score during Free Play",
  "parentPositiveFreePlayNoPositiveP36": "Proportion of intervals with no positive affect during Free Play",
  "parentPositiveFreePlayPositiveP36": "Proportion of intervals with positive affect during Free Play",
  "parentPositiveFreePlayHiPositiveP36": "Proportion of intervals with high positive affect during Free Play",
  "parentPositivePhoneCallPositiveAffect36": "Weighted parent positive affect score during Phone Call",
  "parentPositivePhoneCallNoPositiveP36": "Proportion of intervals with no positive affect during Phone Call",
  "parentPositivePhoneCallPositiveP36": "Proportion of intervals with positive affect during Phone Call",
  "parentPositivePhoneCallHiPositiveP36": "Proportion of intervals with high positive affect during Phone Call",
  "parentPositiveToyCleanUpPositiveAffect36": "Weighted parent positive affect score during Toy Cleanup",
  "parentPositiveToyCleanUpNoPositiveP36": "Proportion of intervals with no positive affect during Toy Cleanup",
  "parentPositiveToyCleanUpPositiveP36": "Proportion of intervals with positive affect during Toy Cleanup",
  "parentPositiveToyCleanUpHiPositiveP36": "Proportion of intervals with high positive affect during Toy Cleanup",

  "parentPositiveFreePlayChildPres42": "Parent Positive Free Play - Other Child Present?",
  "parentPositiveFreePlayIntervals42": "Parent Positive Free Play - Total Number of Intervals",
  "parentPositivePhoneCallChildPres42": "Parent Positive Phone Call - Other Child Present?",
  "parentPositivePhoneCallIntervals42": "Parent Positive Phone Call - Total Number of Intervals",
  "parentPositiveToyCleanupChildPres42": "Parent Positive Toy Cleanup - Other Child Present?",
  "parentPositiveToyCleanupIntervals42": "Parent Positive Toy Cleanup - Total Number of Intervals",
  "parentPositiveFreePlayPositiveAffect42": "Weighted parent positive affect score during Free Play",
  "parentPositiveFreePlayNoPositiveP42": "Proportion of intervals with no positive affect during Free Play",
  "parentPositiveFreePlayPositiveP42": "Proportion of intervals with positive affect during Free Play",
  "parentPositiveFreePlayHiPositiveP42": "Proportion of intervals with high positive affect during Free Play",
  "parentPositivePhoneCallPositiveAffect42": "Weighted parent positive affect score during Phone Call",
  "parentPositivePhoneCallNoPositiveP42": "Proportion of intervals with no positive affect during Phone Call",
  "parentPositivePhoneCallPositiveP42": "Proportion of intervals with positive affect during Phone Call",
  "parentPositivePhoneCallHiPositiveP42": "Proportion of intervals with high positive affect during Phone Call",
  "parentPositiveToyCleanUpPositiveAffect42": "Weighted parent positive affect score during Toy Cleanup",
  "parentPositiveToyCleanUpNoPositiveP42": "Proportion of intervals with no positive affect during Toy Cleanup",
  "parentPositiveToyCleanUpPositiveP42": "Proportion of intervals with positive affect during Toy Cleanup",
  "parentPositiveToyCleanUpHiPositiveP42": "Proportion of intervals with high positive affect during Toy Cleanup",

  "parentPositiveFreePlayChildPres54": "Parent Positive Free Play - Other Child Present?",
  "parentPositiveFreePlayIntervals54": "Parent Positive Free Play - Total Number of Intervals",
  "parentPositivePhoneCallChildPres54": "Parent Positive Phone Call - Other Child Present?",
  "parentPositivePhoneCallIntervals54": "Parent Positive Phone Call - Total Number of Intervals",
  "parentPositiveToyCleanupChildPres54": "Parent Positive Toy Cleanup - Other Child Present?",
  "parentPositiveToyCleanupIntervals54": "Parent Positive Toy Cleanup - Total Number of Intervals",
  "parentPositiveFreePlayPositiveAffect54": "Weighted parent positive affect score during Free Play",
  "parentPositiveFreePlayNoPositiveP54": "Proportion of intervals with no positive affect during Free Play",
  "parentPositiveFreePlayPositiveP54": "Proportion of intervals with positive affect during Free Play",
  "parentPositiveFreePlayHiPositiveP54": "Proportion of intervals with high positive affect during Free Play",
  "parentPositivePhoneCallPositiveAffect54": "Weighted parent positive affect score during Phone Call",
  "parentPositivePhoneCallNoPositiveP54": "Proportion of intervals with no positive affect during Phone Call",
  "parentPositivePhoneCallPositiveP54": "Proportion of intervals with positive affect during Phone Call",
  "parentPositivePhoneCallHiPositiveP54": "Proportion of intervals with high positive affect during Phone Call",
  "parentPositiveToyCleanUpPositiveAffect54": "Weighted parent positive affect score during Toy Cleanup",
  "parentPositiveToyCleanUpNoPositiveP54": "Proportion of intervals with no positive affect during Toy Cleanup",
  "parentPositiveToyCleanUpPositiveP54": "Proportion of intervals with positive affect during Toy Cleanup",
  "parentPositiveToyCleanUpHiPositiveP54": "Proportion of intervals with high positive affect during Toy Cleanup",


  "parentalControlFreePlayChildPres36": "Parental Control Free Play - Other Child Present? (36 months)",
  "parentalControlFreePlayNoInvolvementP36": "Proportion of coded intervals with no involvement during Free Play (36 months)",
  "parentalControlFreePlayVisualContactOnlyP36": "Proportion of coded intervals with visual contact only during Free Play (36 months)",
  "parentalControlFreePlaySocialExchangeP36": "Proportion of coded intervals with social exchange during Free Play (36 months)",
  "parentalControlFreePlaySocialExchangePhysicalP36": "Proportion of coded intervals with social exchange & physical contact during Free Play (36 months)",
  "parentalControlFreePlayGentleControlP36": "Proportion of coded intervals with guidance/gentle control during Free Play (36 months)",
  "parentalControlFreePlayGentleControlPhysicalP36": "Proportion of coded intervals with guidance/gentle control & physical contact during Free Play (36 months)",
  "parentalControlFreePlayNegativeControlP36": "Proportion of coded intervals with negative control during Free Play (36 months)",
  "parentalControlFreePlayNegativeControlPhysicalP36": "Proportion of coded intervals with negative control & physical contact during Free Play (36 months)",
  "parentalControlPhoneCallChildPres36": "Parental Control Phone Call - Other Child Present? (36 months)",
  "parentalControlPhoneCallNoInvolvementP36": "Proportion of coded intervals with no involvement during Phone Call task (36 months)",
  "parentalControlPhoneCallVisualContactOnlyP36": "Proportion of coded intervals with visual contact only during Phone Call task (36 months)",
  "parentalControlPhoneCallSocialExchangeP36": "Proportion of coded intervals with social exchange during Phone Call task (36 months)",
  "parentalControlPhoneCallSocialExchangePhysicalP36": "Proportion of coded intervals with social exchange & physical contact during Phone Call task (36 months)",
  "parentalControlPhoneCallGentleControlP36": "Proportion of coded intervals with guidance/gentle control during Phone Call task (36 months)",
  "parentalControlPhoneCallGentleControlPhysicalP36": "Proportion of coded intervals with guidance/gentle control & physical contact during Phone Call task (36 months)",
  "parentalControlPhoneCallNegativeControlP36": "Proportion of coded intervals with negative control during Phone Call task (36 months)",
  "parentalControlPhoneCallNegativeControlPhysicalP36": "Proportion of coded intervals with negative control & physical contact during Phone Call task (36 months)",
  "parentalControlToyCleanupChildPres36": "Parental Control Toy Cleanup - Other Child Present? (36 months)",
  "parentalControlToyCleanupNoInvolvementP36": "Proportion of coded intervals with no involvement during Toy Cleanup task (36 months)",
  "parentalControlToyCleanupVisualContactOnlyP36": "Proportion of coded intervals with visual contact only during Toy Cleanup task (36 months)",
  "parentalControlToyCleanupSocialExchangeP36": "Proportion of coded intervals with social exchange during Toy Cleanup task (36 months)",
  "parentalControlToyCleanupSocialExchangePhysicalP36": "Proportion of coded intervals with social exchange & physical contact during Toy Cleanup task (36 months)",
  "parentalControlToyCleanupGentleControlP36": "Proportion of coded intervals with guidance/gentle control during Toy Cleanup task (36 months)",
  "parentalControlToyCleanupGentleControlPhysicalP36": "Proportion of coded intervals with guidance/gentle control & physical contact during Toy Cleanup task (36 months)",
  "parentalControlToyCleanupNegativeControlP36": "Proportion of coded intervals with negative control during Toy Cleanup task (36 months)",
  "parentalControlToyCleanupNegativeControlPhysicalP36": "Proportion of coded intervals with negative control & physical contact during Toy Cleanup task (36 months)",
  "parentalControlFreePlayChildPres42": "Parental Control Free Play - Other Child Present? (42 months)",
  "parentalControlFreePlayNoInvolvementP42": "Proportion of coded intervals with no involvement during Free Play (42 months)",
  "parentalControlFreePlayVisualContactOnlyP42": "Proportion of coded intervals with visual contact only during Free Play (42 months)",
  "parentalControlFreePlaySocialExchangeP42": "Proportion of coded intervals with social exchange during Free Play (42 months)",
  "parentalControlFreePlaySocialExchangePhysicalP42": "Proportion of coded intervals with social exchange & physical contact during Free Play (42 months)",
  "parentalControlFreePlayGentleControlP42": "Proportion of coded intervals with guidance/gentle control during Free Play (42 months)",
  "parentalControlFreePlayGentleControlPhysicalP42": "Proportion of coded intervals with guidance/gentle control & physical contact during Free Play (42 months)",
  "parentalControlFreePlayNegativeControlP42": "Proportion of coded intervals with negative control during Free Play (42 months)",
  "parentalControlFreePlayNegativeControlPhysicalP42": "Proportion of coded intervals with negative control & physical contact during Free Play (42 months)",
  "parentalControlPhoneCallChildPres42": "Parental Control Phone Call - Other Child Present? (42 months)",
  "parentalControlPhoneCallNoInvolvementP42": "Proportion of coded intervals with no involvement during Phone Call task (42 months)",
  "parentalControlPhoneCallVisualContactOnlyP42": "Proportion of coded intervals with visual contact only during Phone Call task (42 months)",
  "parentalControlPhoneCallSocialExchangeP42": "Proportion of coded intervals with social exchange during Phone Call task (42 months)",
  "parentalControlPhoneCallSocialExchangePhysicalP42": "Proportion of coded intervals with social exchange & physical contact during Phone Call task (42 months)",
  "parentalControlPhoneCallGentleControlP42": "Proportion of coded intervals with guidance/gentle control during Phone Call task (42 months)",
  "parentalControlPhoneCallGentleControlPhysicalP42": "Proportion of coded intervals with guidance/gentle control & physical contact during Phone Call task (42 months)",
  "parentalControlPhoneCallNegativeControlP42": "Proportion of coded intervals with negative control during Phone Call task (42 months)",
  "parentalControlPhoneCallNegativeControlPhysicalP42": "Proportion of coded intervals with negative control & physical contact during Phone Call task (42 months)",
  "parentalControlToyCleanupChildPres42": "Parental Control Toy Cleanup - Other Child Present? (42 months)",
  "parentalControlToyCleanupNoInvolvementP42": "Proportion of coded intervals with no involvement during Toy Cleanup task (42 months)",
  "parentalControlToyCleanupVisualContactOnlyP42": "Proportion of coded intervals with visual contact only during Toy Cleanup task (42 months)",
  "parentalControlToyCleanupSocialExchangeP42": "Proportion of coded intervals with social exchange during Toy Cleanup task (42 months)",
  "parentalControlToyCleanupSocialExchangePhysicalP42": "Proportion of coded intervals with social exchange & physical contact during Toy Cleanup task (42 months)",
  "parentalControlToyCleanupGentleControlP42": "Proportion of coded intervals with guidance/gentle control during Toy Cleanup task (42 months)",
  "parentalControlToyCleanupGentleControlPhysicalP42": "Proportion of coded intervals with guidance/gentle control & physical contact during Toy Cleanup task (42 months)",
  "parentalControlToyCleanupNegativeControlP42": "Proportion of coded intervals with negative control during Toy Cleanup task (42 months)",
  "parentalControlToyCleanupNegativeControlPhysicalP42": "Proportion of coded intervals with negative control & physical contact during Toy Cleanup task (42 months)",
  "parentalControlFreePlayChildPres54": "Parental Control Free Play - Other Child Present? (54 months)",
  "parentalControlFreePlayNoInvolvementP54": "Proportion of coded intervals with no involvement during Free Play (54 months)",
  "parentalControlFreePlayVisualContactOnlyP54": "Proportion of coded intervals with visual contact only during Free Play (54 months)",
  "parentalControlFreePlaySocialExchangeP54": "Proportion of coded intervals with social exchange during Free Play (54 months)",
  "parentalControlFreePlaySocialExchangePhysicalP54": "Proportion of coded intervals with social exchange & physical contact during Free Play (54 months)",
  "parentalControlFreePlayGentleControlP54": "Proportion of coded intervals with guidance/gentle control during Free Play (54 months)",
  "parentalControlFreePlayGentleControlPhysicalP54": "Proportion of coded intervals with guidance/gentle control & physical contact during Free Play (54 months)",
  "parentalControlFreePlayNegativeControlP54": "Proportion of coded intervals with negative control during Free Play (54 months)",
  "parentalControlFreePlayNegativeControlPhysicalP54": "Proportion of coded intervals with negative control & physical contact during Free Play (54 months)",
  "parentalControlPhoneCallChildPres54": "Parental Control Phone Call - Other Child Present? (54 months)",
  "parentalControlPhoneCallNoInvolvementP54": "Proportion of coded intervals with no involvement during Phone Call task (54 months)",
  "parentalControlPhoneCallVisualContactOnlyP54": "Proportion of coded intervals with visual contact only during Phone Call task (54 months)",
  "parentalControlPhoneCallSocialExchangeP54": "Proportion of coded intervals with social exchange during Phone Call task (54 months)",
  "parentalControlPhoneCallSocialExchangePhysicalP54": "Proportion of coded intervals with social exchange & physical contact during Phone Call task (54 months)",
  "parentalControlPhoneCallGentleControlP54": "Proportion of coded intervals with guidance/gentle control during Phone Call task (54 months)",
  "parentalControlPhoneCallGentleControlPhysicalP54": "Proportion of coded intervals with guidance/gentle control & physical contact during Phone Call task (54 months)",
  "parentalControlPhoneCallNegativeControlP54": "Proportion of coded intervals with negative control during Phone Call task (54 months)",
  "parentalControlPhoneCallNegativeControlPhysicalP54": "Proportion of coded intervals with negative control & physical contact during Phone Call task (54 months)",
  "parentalControlToyCleanupChildPres54": "Parental Control Toy Cleanup - Other Child Present? (54 months)",
  "parentalControlToyCleanupNoInvolvementP54": "Proportion of coded intervals with no involvement during Toy Cleanup task (54 months)",
  "parentalControlToyCleanupVisualContactOnlyP54": "Proportion of coded intervals with visual contact only during Toy Cleanup task (54 months)",
  "parentalControlToyCleanupSocialExchangeP54": "Proportion of coded intervals with social exchange during Toy Cleanup task (54 months)",
  "parentalControlToyCleanupSocialExchangePhysicalP54": "Proportion of coded intervals with social exchange & physical contact during Toy Cleanup task (54 months)",
  "parentalControlToyCleanupGentleControlP54": "Proportion of coded intervals with guidance/gentle control during Toy Cleanup task (54 months)",
  "parentalControlToyCleanupGentleControlPhysicalP54": "Proportion of coded intervals with guidance/gentle control & physical contact during Toy Cleanup task (54 months)",
  "parentalControlToyCleanupNegativeControlP54": "Proportion of coded intervals with negative control during Toy Cleanup task (54 months)",
  "parentalControlToyCleanupNegativeControlPhysicalP54": "Proportion of coded intervals with negative control & physical contact during Toy Cleanup task (54 months)",

  "toyFrustrationFrustration30": "Weighted frustration score",
  "toyFrustrationFrustrationP30": "Proportion of intervals with frustration (mild + overt)",
  "toyFrustrationEngagedP30": "Proportion of intervals in which child was engaged",
  "toyFrustrationSeeksParentP30": "Proportion of intervals in which child sought parent",
  "toyFrustrationNoFrustrationP30": "Proportion of intervals with no frustration",
  "toyFrustrationConcentrationP30": "Proportion of intervals showing concentration",
  "toyFrustrationMildFrustrationP30": "Proportion of intervals showing mild frustration",
  "toyFrustrationOvertFrustrationP30": "Proportion of intervals showing overt frustration",

  "toyFrustrationFrustration36": "Weighted frustration score",
  "toyFrustrationFrustrationP36": "Proportion of intervals with frustration (mild + overt)",
  "toyFrustrationEngagedP36": "Proportion of intervals in which child was engaged",
  "toyFrustrationSeeksParentP36": "Proportion of intervals in which child sought parent",
  "toyFrustrationNoFrustrationP36": "Proportion of intervals with no frustration",
  "toyFrustrationConcentrationP36": "Proportion of intervals showing concentration",
  "toyFrustrationMildFrustrationP36": "Proportion of intervals showing mild frustration",
  "toyFrustrationOvertFrustrationP36": "Proportion of intervals showing overt frustration",

  "toyFrustrationFrustration42": "Weighted frustration score",
  "toyFrustrationFrustrationP42": "Proportion of intervals with frustration (mild + overt)",
  "toyFrustrationEngagedP42": "Proportion of intervals in which child was engaged",
  "toyFrustrationSeeksParentP42": "Proportion of intervals in which child sought parent",
  "toyFrustrationNoFrustrationP42": "Proportion of intervals with no frustration",
  "toyFrustrationConcentrationP42": "Proportion of intervals showing concentration",
  "toyFrustrationMildFrustrationP42": "Proportion of intervals showing mild frustration",
  "toyFrustrationOvertFrustrationP42": "Proportion of intervals showing overt frustration",

  "toyFrustrationFrustration54": "Weighted frustration score",
  "toyFrustrationFrustrationP54": "Proportion of intervals with frustration (mild + overt)",
  "toyFrustrationEngagedP54": "Proportion of intervals in which child was engaged",
  "toyFrustrationSeeksParentP54": "Proportion of intervals in which child sought parent",
  "toyFrustrationNoFrustrationP54": "Proportion of intervals with no frustration",
  "toyFrustrationConcentrationP54": "Proportion of intervals showing concentration",
  "toyFrustrationMildFrustrationP54": "Proportion of intervals showing mild frustration",
  "toyFrustrationOvertFrustrationP54": "Proportion of intervals showing overt frustration",

};
